mcapi_forms.firstpartyform.*:
  type: mapping
  label: 'Designed transaction form'
  mapping:
    id:
      type: string
      label: 'Mcapiform identifier'
    provider:
      type: string
      label: 'Provider'
    title:
      type: label
      label: 'Form title'
    path:
      type: path
      label: 'Path'
    wallet_link_title:
      type: label
      label: Link title to show on wallet
    menu:
      type: mapping
      label: 'Menu'
      mapping:
        title:
          type: string
          label: 'Title'
        weight:
          type: integer
          label: 'Weight'
        menu_name:
          type: string
          label: 'Menu name'
    status:
      type: boolean
      label: Enabled
    type:
      type: string
      label: 'Transaction type'
    incoming:
      type: boolean
      label: 'Direction of payment relative to the current user'
    experience:
      type: mapping
      label: 'Experience'
      mapping:
        twig:
          type: text
          label: Main form
        button:
          type: text
          label: Button label
        preview:
          type: string
          label: Preview mode
    third_party_settings:
      type: sequence
      label: Third party settings
      sequence: { }
