<?php

/*
 * determine which form to edit according to the transaction_type info
 */
function transaction_edit($transaction){
  $types = module_invoke_all('transaction_type_info');
  $type = $types[$transaction->type];
  return drupal_get_form($type['edit'], $transaction);
}


//Some currency properties need to be identical if they are to rendered into the transaction form
//this returns the field only if it is the same in all the passed currencies
//takes top-level fieldnames or data fieldnames
//this is a bit complicated by the design of the currency object, but it works fine
function get_common_currency_properties($currencies, $fieldname) {
  $first = array_pop($currencies);

  foreach ($currencies as $currency) {
    if (isset($first->$fieldname)) {
      if ($first->$fieldname != $currency->$fieldname) {
        return;
      }
      $val = $first->$fieldname;
    }
    elseif (isset($first->data[$fieldname])) {
      if ($first->data[$fieldname] != $currency->data[$fieldname]) {
        return;
      }
      $val = $first->data['$fieldname'];
    }
  }
  if (isset($val)) {
    return $val;
  }
  elseif (isset($first->$fieldname)) {
    return $first->$fieldname;
  }
  elseif (isset($first->data[$fieldname])) {
    return $first->data[$fieldname];
  }
}