<?php
// $Id$: transactions.module,v 1.1.2.4 2009/10/14 10:03:54 matslats Exp $

/*
 * @file
 * Transactions are entered via a form, stored in the database and balances and stats are cached.
 * Permitted users can initiate transactions as another user.
 * Buyers can rates the transaction if ratings are configured.
 * There are 4 transaction types, incoming_confirmed, outoing_confirmed, incoming_direct, outgoing_direct
 * Transaction types are named in config rather than creating a new po file for every community.
 * Many blocks, actions and views are provided
 *
 * This .module file contains only the hooks and functions which might be needed by other modules
 * The inc file contains functions needed to view transactions
 * the admin.inc is needed for processing transactions and changing settings
 * 
 * NOTES ON THE TRANSACTION QUANTITY
 * Quantity is stored as a decimal in the DB for easy calculation
 * The transaction object stores the amount as a decimal fraction
 * In preprocessing  an hour currency the decimal is multiplied by 0.6 to become hours:minutes, 
 * The theme_money function then attaches the icon or currency name
 *
 * if the multiple currencies module is not installed, the default currency id ('cid') is 0
 */
define ('TRANSACTION_STATE_COMPLETED', 0);
define ('TRANSACTION_STATE_PENDING', 1);
define ('TRANSACTION_STATE_ERASED', -1);

/** 
 * http://api.drupal.org/api/function/hook_help/6
 */
function transactions_help($section) {
  switch ($section) {
    case 'admin/help#transaction':
      return t('Defines a contentType called transactions, manages them and does the accounting.');
  }
}
/** 
 * http://api.drupal.org/api/function/hook_init/6
 *
 */
function transactions_cron() {
  //this is for the voluntary reporting function
  if (variable_get('cforge_report', 1)) {
    module_load_include('admin.inc', 'transactions');
    cforge_report();
  }
}

/** 
 * http://api.drupal.org/api/function/hook_init/6
 */
function transactions_init() {
  drupal_add_css(drupal_get_path('module', 'transactions') .'/theme/transaction.css');
}

/**
 * http://api.drupal.org/api/function/hook_node_info/6
 * This hook is required for modules to define one or more node types.
 */
function transactions_node_info() {
  return array(
    'transaction' => array(
      'name' => t('transaction'),
      'module' => 'transactions',
      'description' => t('A movement of a quantity of a currency between two users.'),
      'has_title' => TRUE,
      'title_label' => t('Description of entity traded'),
      'has_body' => FALSE,
    )
  );
}

/*
 * Needed for the views 2 module
 */
function transactions_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'transactions') .'/views',
  );
}

/** 
 * http://api.drupal.org/api/function/hook_menu/6
 */
function transactions_menu() {
  module_load_include('inc', 'transactions');
  $items['admin/marketplace'] = array(
    'title' => 'Complementary Currencies',
    'description' => 'General complementary currency options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cc_options_form'),
    'access callback' => 'user_access',
    'access arguments' => array('configure economy'),
    'file' => 'transactions.admin.inc',
  );
  if (!module_exists('cc_currencies')) {
    $items['admin/marketplace/currency'] = array(
      'title' => 'Default Currency',
      'description' => 'Default currency, transaction ratings and directory settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('default_currency_config'),
      'access arguments' => array('configure economy'),
      'file' => 'transactions.admin.inc',
    );
  }
  $items['admin/marketplace/ratings'] = array(
    'title' => 'Transaction ratings',
    'description' => 'Transaction satisfaction ratings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('transaction_quality_config'),
    'access arguments' => array('configure economy'),
    'file' => 'transactions.admin.inc',
  );
  $items['marketplace/report'] = array(
    'page callback' => 'marketplace_report',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'transactions.admin.inc',
  );
  
  $items['transaction'] = array(
    'title' => 'Create transaction',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('transaction_create_form', NULL, 'starter_completer'),
    'access arguments' => array('use local currency'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'transactions.inc',
    'weight' => 20,
  );
  $items['transaction/start'] = array(
    'title' => 'Initiate',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['transaction/3rdparty'] = array(
    'title' => '3rd party',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('transaction_create_form', NULL, 'payer_payee'),
    'access callback' => 'user_access',
    'access arguments' => array('create 3rdparty transactions'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'transactions.inc',
  );
  $items['transaction/%node/complete'] = array(
    'title' => 'Sign this transaction to finalise it',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('transaction_complete_form', 1),
    'access callback' => 'transactions_access',
    'access arguments' => array('complete', 1),
    'type' => MENU_CALLBACK,
    'file' => 'transactions.inc',
  );
  $items['user/%user/bureau'] = array(
    'title' => 'Bureau',
    'description' => "All transaction information for this user",
    'page callback' => 'transactions_bureau',
    'page arguments' => array(1),
    'access callback' => 'transactions_access',
    'access arguments' => array('bureau', 'transaction', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'file' => 'transactions.inc',
  );
  //we're providing tabs for each stat period, but we should also provide another level of tabs for each currency
  //this setup only works for the default, or first currency
  $periods = variable_get('cc_stats_periods', array("1 month", "1 year"));
  $period = array_shift($periods);
  $firstcurrency = currency_load();
  $items['economy'] = array(
    'title' => 'Economic analysis',
    'description' => 'All available metrics',
    'page callback' => 'show_stats',
    'page arguments' => array($period, 'page'), //this will take a final $cid argument
    'access arguments' => array('view all balances'),
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'transactions.inc',
    'weight' => 20, 
  );
  $items["economy/" . str_replace(' ', '_', $period)] = array(
    'title' => '@period',
    'title arguments' => array('@period' => $period),
    'type' => MENU_DEFAULT_LOCAL_TASK, 
    'weight' => -20, 
  );
  foreach ($periods as $period) {
    $items["economy/" . str_replace(' ', '_', $period)] = array(
      'title' => '@period',
      'title arguments' => array('@period' => $period),
      'page arguments' => array($period, 'page'),
      'access arguments' => array('view all balances'),
      'type' => MENU_LOCAL_TASK, 
    ); 
  }
  return $items;
}

function transactions_menu_alter(&$items) {
  //because we use the custom form transaction/add
  $items['node/add/transaction']['type'] = MENU_CALLBACK;
}

/** 
 * http://api.drupal.org/api/function/hook_access/6
 * this function is called by node_access, and others in this module
 */
function transactions_access($op, $nid=NULL, $account=NULL, $transaction=NULL) {
  global $user;
  if (user_access('edit all transactions')) {
    return TRUE;
  }
  $uid = $account->uid or $uid = $account or $uid = $user->uid;

  if (!$transaction)$transaction = node_load(arg(1));//only used in node/%/edit
  switch ($op) {
    case 'view'://users can always view their own pages
      return user_access('view all transactions') 
      || $uid == $transaction->payee_uid //transactions the present user was involved in
      || $uid == $transaction->payer_uid;
    case 'create':
      return user_access('use local currency');
    case 'update': //this is the permission used by node_access
    case 'edit':
      return $uid == $transaction->starter_uid && $transaction->state == TRANSACTION_STATE_PENDING;
    case 'complete':
      return $uid == $transaction->completer_uid;
    case 'delete':
      return $uid == $transaction->starter_uid && $transaction->state == TRANSACTION_STATE_PENDING;
    case 'bureau':
      module_load_include('inc', 'transactions');
      //this is only visible if the user may, or has ever traded, and if the viewer is the user, or has permission
      return visible_balances($account) && ($user->uid == $uid || user_access('view all balances'));
    default:
      drupal_set_message('transaction_access given unknown op: '. $op);
  }
}

/** 
 * http://api.drupal.org/api/function/hook_perm/6
 * This hook can supply permissions that the module defines,
 */
function transactions_perm() {
  return array(
    'use local currency',
    'view all transactions',
    'view all balances',
    'edit all transactions',
    'create 3rdparty transactions',
    'configure economy'
  );
}

/** 
 * http://api.drupal.org/api/function/hook_load/6
 */
function transactions_load($node) {
  module_load_include('inc', 'transactions');
  $result = db_query(
    'SELECT payer_uid, payee_uid, starter_uid, completer_uid, cid, quantity, transaction_type, quality, n.title, t.state
      FROM {cc_transactions} AS t
      LEFT JOIN {node} AS n ON n.nid = t.nid
      WHERE n.nid = %d',
    array(':nid' => $node->nid)
  );
  //join the passed node with the transaction fields
  foreach (db_fetch_array($result) as $key => $value) {
    $node->{$key} = $value;
  }
  return $node;
}


/** 
 * http://api.drupal.org/api/function/hook_block/6
 */
function transactions_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      //context sensitive to user being displayed
      $blocks['cc_new_transaction']= array(
        'info' => 'Cc '. t('Start transaction'),
        'visibility' => 0,
        'pages' => "transaction*\nadmin*\nnode*edit",
      );
      foreach (variable_get('cc_stats_periods', array("1 month", "1 year")) as $period) {
        $prd=str_replace(' ', '_', $period);
        $blocks["economy-$prd"] = array(
          'info' => 'Cc '. t("@period economy", array('@period' => $period)),
          'cache' => BLOCK_CACHE_GLOBAL,
        );
      }
      return $blocks;
    case 'view':
      module_load_include('inc', 'transactions');
      global $user;
      switch ($delta) {
        case 'cc_user_balances':
          if (user_access('view all transactions') && arg(0) == 'user' && $uid = arg(1)) {
            $account = user_load($uid);
            return array(
              'subject' => t("@user's balances", array('@user' => theme('username', $account))),
              'content' => transactions_user_balances($account->uid),
            );
          }
          break;
        case 'cc_new_transaction':
          if (transactions_access('create')) {
            $transaction = (object)array('starter_uid' => $user->uid);
            if (arg(0) == 'user') {
              if (arg(1) && $user->uid != arg(1)) {
                $account = user_load(arg(1));
                //block will not show on a user's page who can't trade
                if (!user_access('use local currency', $account)) return;
                $transaction->completer_uid = $account->uid;
                $subject = t('Start transaction with @name', array('@name' => strip_tags(theme('username', $account))));
                $subject = str_replace('&amp;', '&', $subject);//hack for SEL coup de pouce
              }
            }
            return array(
              'subject' => $subject ? $subject : t("Start transaction"),
              'content' => drupal_get_form('transaction_create_form', $transaction, 'starter_completer'),
            );
          }
          break;
        default:
          $period = str_replace('_', ' ', substr($delta, 8));
          return array(
            'subject' => t("@period economy", array('@period' => $period)),
            'content' => show_stats($period, 'block'),
          );
      }
  }
}


/**
 * Implementation of hook_forms().
 */
function transactions_forms() {
  //this function makes no difference, at the moment
  $forms['transaction_create_form']['callback'] = 'transaction_create_form';
  $forms['transaction_3rdparty']['callback'] = 'transaction_create_form';
  return $forms;
}

/** 
 * http://api.drupal.org/api/function/hook_form/6
 * Because we have a special multistep form creating the transactions, this hook_form is only used for node editing
 */
function transactions_form(&$node, $form_state) {
  module_load_include('inc', 'transactions');
  //reload the whole transaction, which will include all the other fields
  $transaction=node_load($node->nid);
  switch ($_POST['op']) {
    default:
    case t('Change') ://typically from the 'full edit' link
      drupal_set_title(t('Editing transaction'));
      $form = transaction_base_form($transaction, 'edit', 'payer_payee');
      $form['state']['#default_value'] = intval($form['state']['#default_value']);
      //this stops the node author being overwritten as 0
      $form['name'] = array(
        '#type' => 'hidden',
        '#value' => $GLOBALS['user']->name
      );
      break;
  }
  return $form;
}

/** 
 * http://api.drupal.org/api/function/hook_form_alter/6
 */
function transactions_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_admin_perm':
      $form['#submit'][] = 'refresh_trader_names';
      break;
    case 'node_delete_confirm':
      if ($form['#parameters'][2]->type == 'transaction') {
        drupal_set_title(t('Are you sure you want to delete this transaction?'));
        $form['#prefix'] ='<blockquote>'. $form['#parameters'][2]->title .'</blockquote>';
        if ($form['#parameters'][2]->state == TRANSACTION_STATE_PENDING) {
          $form['description']['#value'] = t('The transation had not been confirmed');
        }
        elseif ($form['#parameters'][2]->state == TRANSACTION_STATE_COMPLETED) {
          $form['description']['#value'] = t('This transaction was confirmed, so the balances of both users will be affected');
        }
      }
      $form['#redirect'] = 'user';
      break;      
    case 'transaction_node_form':
      $form['#theme'] = array('transaction_3rdparty_form');
      $form['buttons']['preview']['#access'] = FALSE;
      foreach (array('revision_information', 'author', 'options') as $key) {
        $form[$key]['access'] = FALSE;
      }
      break;
  } 
}

/** 
 * http://api.drupal.org/api/function/hook_insert/6
 */
function transactions_insert($node) {
  $result = db_query('INSERT INTO {cc_transactions} (
    nid, payer_uid, payee_uid, starter_uid, completer_uid, quantity, cid, transaction_type, quality, state, depends_on
  ) VALUES (%d, %d, %d, %d, %d, %f, %d, "%s", %d, %d, %d)',
    $node->nid, $node->payer_uid, $node->payee_uid, $node->starter_uid, $node->completer_uid, $node->quantity, $node->cid, $node->transaction_type, $node->quality, $node->state, $node->depends_on);
}

/** 
 * http://api.drupal.org/api/function/hook_update/6
 */
function transactions_update($node) {
  db_query("UPDATE {cc_transactions} SET
    payer_uid = '%d', payee_uid = '%d', starter_uid = '%d', completer_uid = '%d', quantity = '%f', cid = '%d', transaction_type = '%s', quality = '%d', state = %d, depends_on = '%d' WHERE nid = '%d' ",
    $node->payer_uid, $node->payee_uid, $node->starter_uid, $node->completer_uid, $node->quantity, $node->cid, $node->transaction_type, $node->quality, $node->state, 0, $node->nid
  );
}

/** 
 * http://api.drupal.org/api/function/hook_delete/6
 */
function transactions_delete($node) {
  module_load_include('admin.inc', 'transactions');
  //the node is deleted, but it leaves this trace in the cc_transactions table
  db_query("UPDATE {cc_transactions} set state  = %d WHERE nid = %d", TRANSACTION_STATE_ERASED, $node->nid);
}

function transactions_view($node, $teaser = FALSE, $page = FALSE) {
  $node->content['body'] = array(
    '#value' => theme('transaction', $node, $teaser, TRUE),
  );
  return $node;
} 


/** 
 * http://api.drupal.org/api/function/hook_user/6
 * This hook is required for modules to define one or more node types.
 */
function transactions_user($op, &$edit, &$account, $category = NULL) {
  $currencies = array();
  switch ($op) {
    case 'load': 
      static $balances; //this can get run rather a lot in some pageloads, so we'll do minicaching here
      $uid = $account->uid;
      if ($uid) {
        //put the user stats into the user object, where the theming layer can see them
        $result = db_query(
          "SELECT cid, cleared_balance, pending_difference, pending_balance, gross_income, gross_expenditure, quality_mean
            FROM {cc_balance_cache} WHERE uid = %d",
          array(':uid' => $uid)
        );
        while ($balance = db_fetch_array($result)) {
          $cid = array_shift($balance);
          $currency = currency_load($cid);
          //this is tricky and subtly different in version 2.0
          //balances are stored in the user object, but if they are null, they are overwritten by the curreny limits
          $balance += array('min_balance' => $currency->min_balance, 'max_balance' => $currency->max_balance);
          if ($account->balances[$cid]['min_balance']=='') unset ($account->balances[$cid]['min_balance']);
          if ($account->balances[$cid]['max_balance']=='') unset ($account->balances[$cid]['max_balance']);
          //overwrite the stored null limits with the currency defaults
          //and add the all the balances out of the database to the user object
          $balances[$uid][$cid] = (array)$account->balances[$cid] + $balance;
        }
      }
      $account->balances = $balances[$uid];
      break;

    case 'form':
      if ($category != 'account') return;

    case 'register':
      $currencies = currencies_load(array('uids' => array($account->uid)));
      if (!module_exists('contact')) { //buggers up if the fieldset is declared twice
        $form['contact']['#type'] = 'fieldset';
        $form['contact']['#title'] = t('Contact preferences');
      }
      $form['contact']['completer_notification'] = array(
        '#type' => 'checkbox',
        '#prefix' => '<a id="notifications"></a>',
        '#title' => t('Receive email notification when someone initiates a transaction with you'),
        '#default_value' => intval($account->completer_notification),
        '#weight' => 2,
      );
      $form['contact']['starter_notification'] = array(
        '#type' => 'checkbox',
        '#prefix' => '<a id="notifications"></a>',
        '#title' => t('Receive email notification when you start a transaction'),
        '#default_value' => intval($account->starter_notification),
        '#weight' => 2,
      );
      //fields for individual balance limits
      if (user_access('edit all transactions')) {
        $form['balance_limits'] = array(
          '#type' => 'fieldset',
          '#title' => t('Personal balance limits (accountant only)'),
          '#description' => t("Each of these values will override the currency's limits (shown in brackets)"),
          '#weight' => -5,
          '#attributes' => array('class' => 'balance-limits')
        );
        if (user_access('use local currency', $account)) {
          foreach ($currencies as $cid => $currency) {
            $form['balance_limits']['currency-'. $cid] = array(
              '#type' => 'fieldset',
              '#title' => $currency->title,
              '#weight' => $cid,
            );
            //because the overridden balance limits were loaded into the user object,
            //we retrieve them afresh from the db
            $data = unserialize(db_result(db_query("SELECT data from {users} WHERE uid = %d", array(':uid' => $account->uid))));
            $form['balance_limits']['currency-'. $cid]['max-'. $cid] = array(
              '#type' => 'textfield',
              '#title' => t('max limit'),
              '#maxlength' => 6,
              '#default_value' => $data['balances'][$cid]['max_balance'],
              '#field_suffix' =>' ('. $currency->max_balance .')',
            );
            $form['balance_limits']['currency-'. $cid]['min-'. $cid] = array(
              '#type' => 'textfield',
              '#title' => t('min limit'),
              '#maxlength' => 6,
              '#default_value' => $data['balances'][$cid]['min_balance'],
              '#field_suffix' =>' ('. $currency->min_balance .')',
            );
          }
        }
      }
      return $form;
      
    case 'validate':
      if (user_access('edit all transactions')) { //this is extra security. Most users won't have seen these form fields
        $currencies = currencies_load(array('uids' => array($account->uid)));
        foreach ($currencies as $cid => $currency) {
          if ($edit['min-'. $cid] == '' && $edit['max-'. $cid] == '') continue;
          module_load_include('admin.inc', 'transactions');
          validate_limits(array(
            'min-'. $cid => $edit['min-'. $cid],
            'max-'. $cid => $edit['max-'. $cid],
          ), FALSE); 
        }
      }
      break;
      
    case 'insert':
      //user preference to be sent emails about pending transactions
      $edit['starter_notification'] = $edit['notifications'];
      $edit['completer_notification'] = $edit['notifications'];
      //this creates an empty row in {cc_balance_cache} for the first currency on the system //not necessary, I think.
      $currencies = currencies_load();
      foreach ($currencies as $currency) {
        db_query("INSERT INTO {cc_balance_cache} (uid, cid, cleared_balance, pending_balance, pending_difference, gross_income, gross_expenditure) VALUES (%d, %d, 0,0,0,0,0)", array(':uid' => $account->uid, ':cid' => $currency->cid));
      }
      //following on...

    case 'update':
      if (user_access('edit all transactions')) {
        $currencies = currencies_load(array('uids' => array($account->uid)));
        foreach ($currencies as $cid => $currency) {
          $edit['balances'][$cid]['min_balance'] = $edit['min-'. $cid];
          $edit['balances'][$cid]['max_balance'] = $edit['max-'. $cid];
          unset($edit['min-'. $cid]);
          unset($edit['max-'. $cid]);
        }
      }
      //following on...

    case 'after_update':
        module_load_include('admin.inc', 'transactions');
        refresh_trader_names();
      break;

    case 'delete':
      db_query("DELETE from {cc_balance_cache} WHERE uid = %d", array(':uid' => $account->uid));
  }
}

function transactions_nodeapi(&$node, $op) {
  if ($node->type != 'transaction') return;
  module_load_include('inc', 'transactions');
  switch ($op) {
    case 'validate':
      if (!count(form_get_errors()) && $node->payer_uid && $node->payee_uid) {
        $errors = _transaction_user_limits(user_load($node->payer_uid), -$node->quantity, intval($node->cid));
        $errors .= _transaction_user_limits(user_load($node->payee_uid), +$node->quantity, intval($node->cid));
        if (strlen($errors)) {
          //permitted users can override the balance limits
          //this decision should be moved upwards for version 2.0
          if (user_access('edit all transactions')) {
            drupal_set_message($errors, 'warning');
          }
          else {
            form_set_error('quantity', $errors);
          }
        }
      }
      break;

    case 'insert':
      module_load_include('admin.inc', 'transactions');
      //gets rid of any boring status messages
      drupal_get_messages('status', TRUE);
      //3rdparty transactions will not receive any notification, for now. See version 2.0
      if (!strpos($node->transaction_type, 'party')) {
        //automatically trigger the notifications
        $result = db_query("SELECT aid FROM {actions} WHERE callback = 'transactions_email_starter_action' OR callback = 'transactions_email_completer_action'");
        while ($aid = db_result($result)) {
          actions_do($aid, $node, array(
            'hook' => 'nodeapi',
            'op' => $op
          ));
        }
      }
      // the 'break' is missing deliberately
    case 'update':
    case 'delete':
      module_load_include('admin.inc', 'transactions');
      recalculate_balances($node->payer_uid, $node->cid);
      recalculate_balances($node->payee_uid, $node->cid);
      stats_refresh(intval($node->cid));
  }
}

/** 
 * http://api.drupal.org/api/function/hook_theme/6
 * This hook is required for modules to define one or more node types.
 */
function transactions_theme($existing, $type, $theme, $path) {
  $templates_dir = drupal_get_path('module', 'transactions') .'/theme';
  //we load the inc so it's aware of the preprocess functions
  module_load_include('inc', 'transactions');
  module_load_include('admin.inc', 'transactions');
  return array(
    'transaction_starter_form' => array(
      'template' => 'transaction-starter-form',
      'path' => $templates_dir,
      'arguments' => array(
        'form' => NULL,
      ),
    ),
    'transaction_3rdparty_form' => array(
      'template' => 'transaction-3rdparty-form',
      'path' => $templates_dir,
      'arguments' => array(
        'form' => NULL,
      ),
    ),
    'bureau' => array(
      'template' => 'bureau',
      'path' => $templates_dir,
      'arguments' => array(
        'account' => NULL
      )
    ),
    'money' => array(
      'template' => 'money',
      'path' => $templates_dir,
      'arguments' => array(
        'quantity' => 0,
        'cid' => 0
      )
    ),
    'balances' => array(
      'template' => 'balances',
      'path' => $templates_dir,
      'arguments' => array(
        'balances' => array(),
        'currencies' => array(),
      )
    ),
    'stats_block' => array(
      'arguments' => array(
        'stats' => array(),
      )
    ),
    'stats_page' => array(
      'arguments' => array(
        'stats' => array(),
      )
    ),
    'statement' => array(
      'template' => 'statement',
      'path' => $templates_dir,
      'arguments' => array(
        'account' => NULL,
        'transactions' => array(),
      )
    ),
    'rating' => array(
      'arguments' => array(
        'quality' => NULL,
      )
    ),
    'balance_history' => array(
      'template' => 'balance_history',
      'path' => $templates_dir,
      'arguments' => array(
        'account' => NULL,
        'options' => array(),
      )
    ),
    'balance_limits' => array(
      'template' => 'balance_limits',
      'path' => $templates_dir,
      'arguments' => array(
        'account' => NULL,
      )
    ),
    'period_volumes' => array(
      'template' => 'period_volumes',
      'path' => $templates_dir,
      'arguments' => array(
        'account' => NULL,
        'cid' => 0
      )
    ),
    //views fields
    'views_view_field__quantity' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
    'views_view_field__cleared_balance' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
    'views_view_field__pending_difference' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
    'views_view_field__pending_balance' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
    'views_view_field__gross_income' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
    'views_view_field__gross_expenditure' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    ),
  );
}

function theme_views_view_field__quantity($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_transactions_quantity, $row->cc_transactions_cid);
}
function theme_views_view_field__cleared_balance($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_balance_cache_cleared_balance, $row->cc_transactions_cid);
}
function theme_views_view_field__pending_difference($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_balance_cache_pending_difference, $row->cc_transactions_cid);
}
function theme_views_view_field__pending_balance($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_balance_cache_pending_balance, $row->cc_transactions_cid);
}
function theme_views_view_field__gross_income($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_balance_cache_gross_income, $row->cc_transactions_cid);
}
function theme_views_view_field__gross_expenditure($view, $field, $row) {
  if (!isset($row->cc_transactions_cid))$row->cc_transactions_cid = 0;
  return theme('money', $row->cc_balance_cache_gross_expenditure, $row->cc_transactions_cid);
}
/**
* Implementation of hook_theme_registry_alter
*/
function transactions_theme_registry_alter(&$theme_registry) {
  //the 'node' theme callback should include this module's theme directory in its list of paths
  $info = $theme_registry['node']['theme paths'];
  $idx = array_search('modules/node', $info);
  if ($idx !== FALSE) {
    $theme_path = drupal_get_path('module', 'transactions') . '/theme';
    array_splice($theme_registry['node']['theme paths'], $idx+1, 0, $theme_path);
  }
}

/** 
 * http://api.drupal.org/api/function/hook_action_info/6
 * This hook is required for modules to define one or more node types.
 */
function transactions_action_info() {
  module_load_include('inc', 'transactions');
  $actions['transactions_email_completer_action'] = array(
    'description' => t('Send email to transaction completer.') .' '. t('Triggers automatically'),
    'type' => 'node',
    'configurable' => TRUE,
    'hooks' => array(
      'nodeapi' => array('presave'),
    )
  );
  $actions['transactions_email_starter_action'] = array(
    'description' => t('Send email to transaction starter.') .' '. t('Triggers automatically'),
    'type' => 'node',
    'configurable' => TRUE,
    'hooks' => array(
      'nodeapi' => array('presave'),
    )
  );
  return $actions;
}

function transactions_email_completer_action_form($context) {
  return transaction_email_form_template($context);
}
function transactions_email_starter_action_form($context) {
  return transaction_email_form_template($context);
}
function transaction_email_form_template($context) {
  $template = $context['template'] ? $context['template'] : '';
  $vars = _transaction_email_replacements();
  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Message subject'),
    '#default_value' => $context['subject'] ? $context['subject'] : t('Transaction notification'),
    '#description' => t('Tokens cannot be used here'),
  );
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Email template'),
    '#default_value' => $context['template'] ? $context['template'] : t('This is an automated notification.') ."\n\n".
      t('%starter has started a transaction with %completer') ."\n\n".
      t('The transaction was for: %reason') .' '.
      t('You can confirm the transaction from your profile page: %profile_url') ."\n\n".
      t("You can change your mail notification settings by clicking 'edit' on your profile"),
    '#description' => t("This email will be sent to members when someone initiates a transaction with them which needs confirming. ") . 
    t("You can use the following strings as variables:")
  );
  if (module_exists('mime_mail')) {
    $form['message']['#description'] .= t('You can use html in your message.');
  }
  else {
    $form['message']['#description'] .= t('Use only plain text ');
  }
  foreach ($vars as $var => $exp) {
    $form['message']['#description'] .= "\n<br /><strong>$var</strong>: $exp";
  }
  return $form;
}

function transactions_email_completer_action_validate($form, &$form_state) {
  transactions_email_action_validate($form_state);
}
function transactions_email_starter_action_validate($form, &$form_state) {
  transactions_email_action_validate($form_state);
}
function transactions_email_action_validate($form_state) {
  if (!strlen ($form_state['values']['message'])) {
    form_set_error('message', t("You can't send an empty email"));
  }
  if (!strlen ($form_state['values']['subject'])) {
    form_set_error('subject', t("Your mail must have a subject"));
  }
}
function transactions_email_completer_action_submit($form, &$form_state) {
  return array(
    'template' => $form_state['values']['message'],
    'subject' => $form_state['values']['subject']
  );
}
function transactions_email_starter_action_submit($form, &$form_state) {
  return array(
    'template' => $form_state['values']['message'],
    'subject' => $form_state['values']['subject']
  );
}


//takes the transaction node opbject and returns a load of ready to print fields, in an array
function preprocess_transaction_fields($transaction, $uid) {
  $props = array('node' => $transaction);
  $classes = array();
  //this is for the initial confirmation form, before the transaction is saved to db
  if (!$transaction->created) {
    $transaction->created = time();
  }
  $props['submitted'] = format_date($transaction->created, 'small');
  $props['description'] = $transaction->title;
  $props['payer'] = theme('username', user_load($transaction->payer_uid));
  $props['payee'] = theme('username', user_load($transaction->payee_uid));
  $props['amount'] = theme('money', $transaction->quantity, $transaction->cid);
  $props['balance'] = theme('money', $transaction->balance, $transaction->cid);
  $props['classes'][] = $transaction->state ? 'pending' : 'completed';

  if ($transaction->starter_uid) {
    $props['starter'] = theme('username', user_load($transaction->starter_uid));
  }
  if ($transaction->completer_uid) {
    $props['completer'] = theme('username', user_load($transaction->completer_uid));
  }
  if (count($qualities = variable_get('cc_transaction_qualities', array()))) {
    $classes[] = 'quality-'. $transaction->quality;
    $classes[] = $qualities[$transaction->quality];
  }
  if ($transaction->payer_uid == $uid) {
    $props['notme'] = $props['payee'];
  }
  elseif ($transaction->payee_uid == $uid) {
    $props['notme'] = $props['payer'];
  }
  if ($transaction->nid) {
    $props['transaction_link'] = l($transaction->title, 'node/'. $transaction->nid);
  }
  else {
    $props['transaction_link'] = $transaction->title;
  }
  return $props;
}

//returns the specified, first, or default currency object
function currency_load($cid=NULL) {
  if (module_exists('cc_currencies')) {
    $all_currencies = get_currencies();
    if ($cid) {
      return $all_currencies[$cid];
    }
    else {
      return array_shift($all_currencies);
    }
  }
  return variable_get('cc_default_currency', NULL);
}

//always returns an array 
function currencies_load($options=array()) {
  if (module_exists('cc_currencies')) {
    return get_currencies($options);
  }
  return array(0 => variable_get('cc_default_currency', NULL));
}


/*
 * This validates both the default currency and subsequent ones in the cc_multiple module
 */
function currency_validate($form, &$form_state) {
  $currency = (object)$form_state['values'];
  //check that the title is unique amongst currencies
  
  //check that the objective value is blank or numeric
  if ($currency->objective_value != NULL && !is_numeric ($currency->objective_value)) {
    form_set_error('objective_value', t("This must be a number: @value", array('@value' => $currency->objective_value)));
  }
  else {
    //sets blank to zero
    $form_state_['values']['objective_value'] = intval($currency->objective_value);
  }
  
  $divisions = array('integer', 'sixtieths', 'decimal');
  if (!in_array($currency->division, $divisions)) {
    form_set_error('division', t("Invalid option for division: @value", array('@value' => $currency->division)));
  }

  module_load_include('admin.inc', 'transactions');
  validate_limits(array(
    'min_balance' => $currency->min_balance, 
    'max_balance' => $currency->max_balance,
  ), TRUE);
  
  if (strlen($currency->color) < 6) {
    form_set_error('color', t('Color field must be 6 hex characters'));
  }
  
  //check the icon upload
  //does this mean the file is known to the files table? I think not
  $dest = file_directory_path() .'/currencies';
  file_check_directory($dest, TRUE, 'icon_upload');
  if ($file = file_save_upload('icon_upload', NULL, $dest, FALSE)) {
    if ($err = array_pop (file_validate_is_image($file))) {
      form_set_error('icon_upload', $err);
    }
    file_validate_image_resolution($file, "16x16", "12x12");
    //save using the original filename, in case of duplicate
    $form_state['values']['icon'] = $file->filepath;
  }
  
  //if any currency on the system is float then the db fields should be floats too.
  //if the division of this currency has changed...
  $all_currencies = currencies_load();
  //we don't have the nid/cid here so we need to key the all_currencies array by title
  foreach ($all_currencies as $curr) {$named_currencies[$curr->{title}] = $curr;}
  if ($currency->division != $named_currencies[$currency->{title}]->division) {
    //check to see if any currencies are floats and set the db fields accordingly
    $named_currencies[$currency->{title}] = $currency; //because the settings haven't been saved yet
    $div = 'int';
    foreach ($named_currencies as $curr) {
      //three possible values for division: integer, hours, decimal; the last two require float fields.
      if ($curr->division != 'integer') {
        $div ='float';
      }
    }
    module_load_include('admin.inc', 'transactions');
    alter_quantity_field_types($div);
  }
}

function template_preprocess_money(&$vars) {
  $currency = currency_load($vars['cid']);
  $vars['sign'] = '';
  if (is_numeric($vars['quantity'])) {
    //seperate the sign, positive or negative
    $vars['quantity'] = $vars['quantity']+0;
    if ($vars['quantity'] <0) {
      $vars['sign'] = '-';
      $vars['quantity'] = abs($vars['quantity']);
    }
    //convert the division to something presentable
    if ($currency->division == 'sixtieths') {
      $quant = intval($vars['quantity']);
      $remainder = 60*($vars['quantity'] - $quant);
      $vars['quantity'] = sprintf('%d:%02d', $quant, $remainder);
    }
  }
  if (strlen($currency->icon)) {
    if (module_exists('cc_currencies')) {
      $vars['icon'] = l(theme_image($currency->icon), 'node/'. $currency->nid, array('html' => TRUE, 'attributes' => array('title' => $currency->title .' - '. $currency->body, 'alt' => $currency->title)));
    }
    else {
      $vars['icon'] = theme_image($currency->icon, t('Currency Icon'), $currency->title);
    }
  }
  $vars['name'] = $currency->title;
}

/*
 * Returns an array of transaction_types belonging to this module which have been named
 */
function _named_transaction_types() {
  $names = variable_get('cc_transaction_types', array());
  $types = $names['transactions'];
  if (!count($types)) {
    drupal_set_message(t('There are no transaction types declared on the system. Please go to admin/marketplace and name some transaction types')); 
  } 
  return $types;
}

function get_trader_list() {
  $data = cache_get('cc_trader_list');
  if (!$data) {
    module_load_include('admin.inc', 'transactions');
    refresh_trader_names();
    $data = cache_get('cc_trader_list');
  }
  return $data->data;
}

  

//options might equal
function generate_transaction_node($title, $payer_uid, $payee_uid, $quantity, $options = array(), $cid=0) {
  global $user;
  if ($quantity <= 0) {
    drupal_set_message(t('@function was asked to create a transaction with negative value: @value', 
      array('@function' => 'generate_transaction_node', '@value' => $quantity)
    ));
    return;
  }
  $node = $options + array(
   //default options
    'state' => TRANSACTION_STATE_COMPLETED,
    'transaction_type' => 'api unspecified',
    'quality' => NULL,
    'starter_uid' => $user->uid,
    'completer_uid' => $user->uid == $payer_uid ? $payee_uid : $payer_uid,
    'uid' => $user->uid,
    'created' => time(),
   //other incoming arguments
    'cid' => $cid,
    'payee_uid' => $payee_uid,
    'payer_uid' => $payer_uid,
    'quantity' => $quantity,
    'title' => $title,
   //some basic node properties
    'type' => 'transaction',
    ////this adds protection against anonymous users seeing transactions
    //if transactions_access isn't working properly
    'status' => 0,
  );
  $node=(object)$node;
  node_save($node);
  return $node;
}