<?php

/**
 * @file
 * Hooks for mcapi_greco module
 */

use Drupal\mcapi\Entity\Currency;
use Drupal\mcapi\Entity\CurrencyInterface;

function mcapi_greco_gchart() {
  return array(
    '#theme' => 'greco_gchart',
    '#attached' =>array('library' => array('https://www.google.com/jsapi')),//how to put this in the theme layer
  );
}

//pull all the data out and produce a gchart
//see the balance_history_gchart...
function template_preprocess_greco_gchart() {


}

function mcapi_greco_theme() {
  return array(
    'greco_gchart' => array(
      'render_element' => 'element'
    )
  );
}

/*
 * Implements hook_cron().
 * Greco says:
 * Dividing the sum of all the debit balances by the average daily sales gives us the sales performance ratio for the system.
 */
function mcapi_index_views_cron() {
  $sample_period = 90;
  $manager = \Drupal::entityTypeManager()->getStorage('mcapi_transaction');
  foreach (Currency::loadMultiple() as $curr_id => $currency) {
    if ($currency->issuance != CurrencyInterface::TYPE_PROMISE) continue;
    $sum_of_all_debit_balances = 0;

    //get the sum of all debit balances (in this currency) of all wallets
    foreach ($manager->balances($curr_id) as $balance) {
      if ($balance > 0) {
        $sum_of_all_debit_balances += $balance;
      }
    }
    //now get the average daily sales
    $total_daily_sales = \Drupal::entityTypeManager()->getStorage('mcapi_transaction')->volume(
      $curr_id,
      ['since' => strtotime(-$sample_period .' days')]
    );
    $average_daily_sales = round($total_daily_sales / $sample_period);

    if ($average_daily_sales) {
      $indicator = round($sum_of_all_debit_balances / $average_daily_sales, 1);
    }
    else {
      $indicator = NULL;
    }

    db_insert('mcapi_greco')
      ->fields(array('curr_id' => $curr_id, 'timestamp' => REQUEST_TIME, 'value' => $indicator))
      ->execute();
  }
}

