id: mcapi_transaction.mcapi_transaction.default
uuid: 54644610-6145-4a61-8201-1d083f7b015f
targetEntityType: mcapi_transaction
bundle: mcapi_transaction
mode: default
content:
  field_categories:
    type: taxonomy_term_reference_link
    weight: '6'
    settings: {  }
    label: above
  payer:
    weight: '0'
    visible: true
  payee:
    weight: '1'
    visible: true
  worths:
    weight: '2'
    visible: true
  description:
    weight: '3'
    visible: true
  state:
    weight: '4'
    visible: true
  type:
    weight: '5'
    visible: true
status: true
