id: admin
uuid: 9c78b898-53c3-4bc4-b95a-90624c392433
label: Administrator
weight: 6
permissions:
  - 'administer blocks'
  - 'configure mcapi'
  - 'bypass node access'
  - 'administer content types'
  - 'administer modules'
  - 'administer site configuration'
  - 'administer themes'
  - 'administer software updates'
  - 'administer permissions'
status: true
langcode: en
