<?php

use Drupal\mcapi\Entity\CurrencyInterface;
use Drupal\mcapi\Entity\WalletInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * implements hook_entity_type_alter().
 */
function mcapi_limits_entity_type_alter(array &$entity_types) {
  $constraints = $entity_types['mcapi_transaction']->getConstraints();
  $constraints['Limits'] = [];
  $entity_types['mcapi_transaction']
    ->setConstraints($constraints);
}

/**
 * implements hook_form_FORM_ID_alter().
 * Add the limits section to the currency form
 */
function mcapi_limits_form_mcapi_currency_edit_form_alter(&$form, $form_state) {
  $form_state->loadInclude('mcapi_limits', 'inc');
  _mcapi_limits_form_mcapi_currency_edit_form_alter($form, $form_state);
}

/**
 * Implements hook_theme().
 */
function mcapi_limits_theme($existing, $type, $theme, $path){
  return [
    'mcapi_limits_absolute' => [
      'template' => 'mcapi_limits_absolute',
      'variables' => [
        'currency' => NULL,
        'wallet' => NULL,
      ],
      'file' => 'mcapi_limits.inc'
    ],
    'mcapi_limits_relative' => [
      'template' => 'mcapi_limits_relative',
      'variables' => [
        'currency' => NULL,
        'wallet' => NULL,
      ],
      'file' => 'mcapi_limits.inc'
    ],
    //only for exchange currencies
    'mcapi_limits_balanced' => [
      'template' => 'mcapi_limits_balanced',
      'variables' => [
        'currency' => NULL,
        'wallet' => NULL,
        'size' => '100%',
      ],
      'file' => 'mcapi_limits.inc'
    ]
  ];
}

/**
 * implements hook_entity_extra_field_info().
*/
function mcapi_limits_entity_extra_field_info() {
  return [
    'mcapi_wallet' => [
      'mcapi_wallet' => [
        'display' => [
          //will display differently according to the limits settings.
          'balance_limits' => [
            'label' => t('Balance limits'),
            'description' => t('Trading limits per currency'),
            'weight' => 0,
          ]
        ]
      ]
    ]
  ];
}

/**
 * implement hook_ENTITY_TYPE_view().
 * adds the extra_fields to the wallet view according to the display settings
*/
function mcapi_limits_mcapi_wallet_view(&$build, $wallet, $display, $view_mode) {
  if ($display->getComponent('balance_limits')) {
    module_load_include('inc', 'mcapi_limits');
    $build += mcapi_view_limits($wallet);
  }
}
