mcapi.settings:
  type: config_object
  label: 'Other configuration'
  mapping:
    sentence_template:
      type: text
      label: Transaction sentence template
    editable:
      type: boolean
      label: Allow transaction records to be edited
    fields:
      type: mapping
      label: Fields
      mapping:
        participants:
          type: boolean
          label: Participants
        description:
          type: boolean
          label: Description
        worth:
          type: boolean
          label: Worth
        type:
          type: boolean
          label: Type
        fieldapi:
          type: boolean
          label: Field API
    worths_delimiter:
      type: string
      label: Delimiter
    zero_snippet:
      type: string
      label: Zero snippet
    counted:
      type: map
      label: Counted transaction states
    mail_errors:
      type: string
      label: Send diagnostics to user 1 by mail
    view:
      type: transaction_relatives
      label: Relatives with view access
    update:
      type: transaction_relatives
      label: Relatives with update access
    payways:
      type: string
      label: Payment direction
    entity_types:
      type: sequence
      label: Max number of wallets
      sequence: { }
    access_personalised:
      type: boolean
      label: 'Personalised wallet access'
    wallet_tab:
      type: boolean
      label: Wallet tab
    wallet_inex_tab:
      type: boolean
      label: Income & expenditure tab
    wallet_log_tab:
      type: boolean
      label: Transaction log tab
    wallet_widget_max_select:
      type: integer
      label: Dropdown threshhold
    wallet_widget_max_radios:
      type: integer
      label: Radio button threshhold
    autoadd:
      type: boolean
      label: 'Auto-create a wallet for every new user'
    render_unused:
      type: boolean
      label: 'Show unused currency stats in wallet view.'
      sequence: { }
    ticks_name:
      type: String
      label: Base accounting unit

mcapi.currency.*:
  type: config_entity
  label: 'Currency'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    description:
      type: label
      label: 'Description'
    uid:
      type: integer
      label: Comptroller
    issuance:
      type: integer
      label: 'Basis of issuance'
    format:
      type: sequence
      label: Format
    zero:
      type: boolean
      label: 'Allow zero transactions'
    color:
      type: string
      label: 'Colour'
    weight:
      type: integer
      label: 'Weight'

mcapi.state.*:
  type: config_entity
  label: Transaction workflow state
  mapping:
    id:
      type: string
      label: State ID
    label:
      type: label
      label: Label
    description:
      type: text
      label: Description
    counted:
      type: boolean
      label: Counted

mcapi.type.*:
  type: config_entity
  label: Transaction workflow
  mapping:
    id:
      type: string
      label: Type ID
    label:
      type: label
      label: Label
    description:
      type: text
      label: Description
    start_state:
      type: string
      label: Initial workflow state
    provider:
      type: string
      label: Module

transaction_relatives:
  type: sequence
  label: Relatives
  sequence: { }

action.configuration.mcapi_transaction.*:
  type: mapping
  label: Transition action settings
  mapping:
    title:
      'type': label
      'label': Title
    tooltip:
      'type': text
      'label': Tooltip
    states:
      'type': sequence
      'label': Applies to states
    page_title:
      'type': text
      'label': Page title
    format:
      'type': string
      'label': Transaction display
    twig:
      'type': text
      'label': Template
    display:
      'type': integer
      'label': Display
    button:
      'type': text
      'label': Button text
    cancel_link:
      'type': text
      'label': Cancel button text
    message:
      'type': text
      'label': Success message
    weight:
      'type': integer
      'label': Weight
    #this is transaction_relatives by default
    access: { }

