mcapi.misc:
  type: mapping
  label: 'Other configuration'
  mapping:
    sentence_template:
      type: text
      label: Transaction sentence template
    editable:
      type: boolean
      label: Allow transaction records to be edited
    fields:
      type: mapping
      label: Fields
      mapping:
        participants: 
          type: boolean
          label: Participants
        description: 
          type: boolean
          label: Description
        worth: 
          type: boolean
          label: Worth
        type: 
          type: boolean
          label: Type
        fieldapi: 
          type: boolean
          label: Field API
    worths_delimiter:
      type: string
      label: Delimiter
    zero_snippet:
      type: string
      label: Zero snippet
    counted:
      type: map
      label: Counted transaction states
    mail_errors:
      type: string
      label: Send diagnostics to user 1 by mail
    active_relatives: 
      type: sequence
      name: Transaction relatives
    active_transitions:
      type: sequence
      name: Active transition plugins

mcapi.wallets:
  type: mapping
  label: Wallet settings
  mapping:
    wallet_access:
      type: mapping
      label: Default wallet access setting
      mapping: 
        wallet_default_viewers:
          type: string
          label: 'Visible to'
        wallet_default_payees:
          type: string
          label: 'Default payees'
        wallet_default_payers:
          type: string
          label: 'Default payers'
    display_format:
      type: boolean
      label: 'Display format'
    entity_types:
      type: sequence
      label: Max number of wallets
      sequence: { }
    access_personalised:
      type: boolean
      label: 'Personalised wallet access'
    autoadd:
      type: boolean
      label: 'Auto-create a wallet for every new user'
    add_link_location:
      type: string
      label: 'Location of the link to create new wallets under an entity'
    details:
      type: map
      label: 'View transaction log'
    summary:
      type: map
      label: 'View summary'
    payin:
      type: map
      label: 'Pay into this wallet'
    payout:
      type: map
      label: 'Pay out of this wallet'

mcapi.currency.*:
  type: config_entity
  label: 'Currency configuration'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    uid:
      type: integer
      label: Comptroller
    issuance:
      type: string
      label: 'Basis of issuance'
    format:
      type: sequence
      label: Format
    zero:
      type: boolean
      label: 'Allow zero transactions'
    color:
      type: string
      label: 'Colour'
    weight:
      type: integer
      label: 'Weight'
    deletion:
      type: integer
      label: Delete options
    #third_party_settings included in definition of config_entity core.data_types.schema.yml
        
mcapi.state.*:
  type: config_entity
  label: Transaction workflow state
  mapping:
    id:
      type: string
      label: State ID
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    counted:
      type: boolean
      label: Counted

mcapi.type.*:
  type: config_entity
  label: Transaction workflow
  mapping:
    id:
      type: string
      label: Type ID
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    start_state:
      type: string
      label: Initial workflow state
  
mcapi.transition.*:
  type: config_entity
  label: Transition settings
  mapping: 
    title:
      'type': string
      'label': Title
    tooltip:
      'type': string
      'label': Tooltip
    states:
      'type': sequence
      'label': Applies to states
    page_title:
      'type': string
      'label': Page title
    format:
      'type': string
      'label': Transaction display
    twig:
      'type': string
      'label': Template
    button:
      'type': string
      'label': Button text
    cancel_button:
      'type': string
      'label': Cancel button text
    format2:
      'type': string
      'label': Confirm form transaction display
    redirect:
      'type': string
      'label': Redirect path
    twig2:
      'type': string
      'label': Template
    message:
      'type': string
      'label': Success message
    weight:
      'type': integer
      'label': Weight
    access:
      'type': sequence
      'label': Access settings
    #third_party_settings included in definition of config_entity core.data_types.schema.yml
