mcapi.misc:
  type: mapping
  label: 'Mutual Credit Misc settings'
  mapping:
    delete_mode:
      type: integer
      label: 'Delete mode'
    show_balances:
      type: boolean
      label: 'Show balances'
    change_undo_mode:
      type: boolean
      label: Change undo mode
    sentence_template:
      type: text
      label: Transaction sentence template
    mix_mode:
      type: boolean
      label: Allow more than one currency in transactions

mcapi.currency.settings.decimal:
  type: mapping
  label: Decimal Currency Settings
  mapping:
    scale:
      type: integer
      label: Number of Decimals

mcapi.currency.settings.time:
  type: mapping
  label: Time Currency Settings

mcapi.currency.widget.currency_time_single:
  type: mapping
  label: Single Time Widget Settings
  mapping:
    placeholder:
      type: string
      label: Placeholder for the text field.

mcapi.currency.widget.currency_decimal_single:
  type: mapping
  label: Single Decimal Widget Settings
  mapping:
    placeholder:
      type: string
      label: Placeholder for the text field.

mcapi.currency.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    status:
      type: boolean
      label: Enabled
    isuance:
      type: string
      label: 'Basis of issuance'
    uid:
      type: integer
      label: 'Declared by'
    reservoir:
      type: integer
      label: 'Reservoir account'
    type:
      type: string
      label: 'Type'
    settings:
      type: mcapi.currency.settings.[%parent.type]
    widget:
      type: string
      label: 'Widget'
    widget_settings:
      type: mcapi.currency.widget.[%parent.widget]
    formatter:
      type: string
      label: 'Formatter'
    formatter_settings:
      type: mcapi.currency.formatter.[%parent.formatter]
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'
    zero:
      type: string
      label: 'Zero value display'
    color:
      type: string
      label: 'Colour'
    access:
      type: mapping
      label: 'Currency access'
      mapping:
        membership:
          type: string
          label: 'Use the currency'
        trader_data:
          type: string
          label: 'View aggregated user transaction data'
        system_data:
          type: string
          label: 'View aggregated system data'
    view_transaction_states:
      type: sequence
      label: 'Privacy'
      sequence:
        - type: sequence
          label: 'Transaction in state'
          sequence:
            - type: boolean
              label: 'Enabled'
    access_operations:
      type: sequence
      label: 'Transaction operations'
      sequence:
        - type: sequence
          label: 'Operation'
          sequence:
            - type: boolean
              label: 'Enabled'
    weight:
      type: integer
      label: 'Weight'


mcapi.operation.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    subject:
      type: string
      label: Subject
    body:
      type: text
      label: Body
    cc:
      type: string
      label: Copy to

mcapi.1stparty.*
  type: mapping
  label: 'Mcapi form configuration'
  mapping:
    id:
      type: string
      label: 'Mcapiform identifier'
    title:
      type: label
      label: 'Form title'
    status:
      type: boolean
      label: Enabled
    type:
      type: string
      label: 'Transaction type'
    partner:
      type: mapping
      label: 'Settings for partner field'
      mapping:
        user_chooser_config:
          type: string
          label: 'Users to choose from'
        preset:
          type: integer
          label: 'Preset trading partner'
    direction:
      type: mapping
      label: 'Direction of payment'
      mapping:
        preset:
          type: string
          label: 'Preset direction'
    description:
      type: mapping
      label: 'Reason for payment'
      mapping:
        preset:
          type: string
          label: 'Preset description'
    worths:
      type: mapping
      label: 'Quantity of payment'
      mapping:
        preset:
          type: array
          label: 'Preset quantity'
    created:
      type: mapping
      label: 'Date field'
      mapping:
        preset:
          type: boolean
          label: 'Show date widget'
    step1:
      type: mapping
      label: 'Step 1'
      mapping:
        template1:
          type: text
          label: Main form
        button1:
          type: text
          label: Button label
        next1:
          type: text
          label: Button label
    step2:
      type: mapping
      label: 'Step 2'
      mapping:
        format2:
          type: text
          label: Display format
        template2:
          type: text
          label: Main form
        button2:
          type: text
          label: Button label
        next2:
          type: text
          label: Outcome
        redirect:
          type: text
          label: Redirect path
    message:
      type: text
      label: Confirmation message
