mcapi.misc:
  type: mapping
  label: 'Mutual Credit Misc settings'
  mapping:
    delete_mode:
      type: integer
      label: 'Delete mode'
    show_balances:
      type: boolean
      label: 'Show balances'
    change_undo_mode:
      type: boolean
      label: Change undo mode
    sentence_template:
      type: text
      label: Transaction sentence template
    mix_mode:
      type: boolean
      label: Allow more than one currency in transactions


mcapi.currency.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    insurance:
      type: string
      label: 'Insurance type'
    uid:
      type: integer
      label: 'Declared by'
    reservoir:
      type: integer
      label: 'Reservoir account'
    display:
      type: mapping
      label: 'Appearence'
      mapping:
        type:
          type: string
          label: 'Type'
        widget:
          type: integer
          label: 'Widget'
        granularity:
          type: integer
          label: 'Granularity'
        delimiter:
          type: string
          label: 'Delimiter'
        select:
          type: text
          label: 'Options'
        divisions:
          type: sequence
          label: 'Divisions'
          sequence:
            - type: string
              label: 'Division'
        prefix:
          type: string
          label: 'Prefix'
        suffix:
          type: string
          label: 'Suffix'
        zero:
          type: string
          label: 'Zero value display'
    access:
      type: mapping
      label: 'Currency access'
      mapping:
        membership:
          type: string
          label: 'Use the currency'
        trader_data:
          type: string
          label: 'View aggregated user transaction data'
        system_data:
          type: string
          label: 'View aggregated system data'
    view_transaction_states:
      type: sequence
      label: 'Privacy'
      sequence:
        - type: sequence
          label: 'Transaction in state'
          sequence:
            - type: boolean
              label: 'Enabled'
    access_operations:
      type: sequence
      label: 'Transaction operations'
      sequence:
        - type: sequence
          label: 'Operation'
          sequence:
            - type: boolean
              label: 'Enabled'
    weight:
      type: integer
      label: 'Weight'


mcapi.operation.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    subject:
      type: string
      label: Subject
    body:
      type: text
      label: Body
    cc:
      type: string
      label: Copy to
