mcapi.misc:
  type: mapping
  label: 'Other configuration'
  mapping:
    sentence_template:
      type: text
      label: Transaction sentence template
    mix_mode:
      type: boolean
      label: Allow more than one currency in transactions
    exchange_menu:
      type: string
      label: Menu
    worths_delimiter:
      type: string
      label: Delimiter
    child_errors:
      type: mapping
      label: Invalid child transactions
      mapping:
        mail_user1:
          type: string
          label: Send diagnostics to user 1 by mail
        allow:
          type: string
          label: Allow the parent transaction
        watchdog:
          type: string
          label: Log a warning
        show_messages:
          type: string
          label: Show warning messages to user
    indelible:
      type: string
      label: Indelible accounting

mcapi.wallets:
  type: mapping
  label: Wallet settings
    wallet_access:
      type: mapping
      label: Default wallet access setting
      mapping: 
        wallet_default_viewers:
          type: string
          label: 'Visible to'
        wallet_default_payees:
          type: string
          label: 'Default payees'
        wallet_default_payers:
          type: string
          label: 'Default payers'
    unique_names:
      type: boolean
      label: 'Unique wallet names'
    display_format:
      type: boolean
      label: 'Display format'
    unique_names:
      type: boolean
      label: 'Unique wallet names'
    access_personalised:
      type: boolean
      label: 'Personalised wallet access'
    autoadd_name:
      type: string
      label: 'Name of auto-added wallet'

mcapi.currency.settings.decimal:
  type: mapping
  label: Decimal Currency Settings
  mapping:
    scale:
      type: integer
      label: Number of Decimals

mcapi.currency.settings.time:
  type: mapping
  label: Time Currency Settings

mcapi.currency.widget.currency_time_single:
  type: mapping
  label: Single Time Widget Settings
  mapping:
    placeholder:
      type: string
      label: Placeholder for the text field.

mcapi.currency.widget.currency_decimal_single:
  type: mapping
  label: Single Decimal Widget Settings
  mapping:
    placeholder:
      type: string
      label: Placeholder for the text field.

mcapi.currency.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    status:
      type: boolean
      label: Enabled
    uid:
      type: integer
      label: Comptroller
    isuance:
      type: string
      label: 'Basis of issuance'
    type:
      type: string
      label: 'Type'
    settings:
      type: mcapi.currency.settings.[%parent.type]
    widget:
      type: string
      label: 'Widget'
    widget_settings:
      type: mcapi.currency.widget.[%parent.widget]
    formatter:
      type: string
      label: 'Formatter'
    formatter_settings:
      type: mcapi.currency.formatter.[%parent.formatter]
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'
    zero:
      type: string
      label: 'Zero value display'
    color:
      type: string
      label: 'Colour'
    weight:
      type: integer
      label: 'Weight'
    limits_plugin:
      type: string
      label: Plugin
    limits_settings:
      type: type: mcapi.currency.limits.[%parent.formatter]
      label: Settings

#this doesn't include per-plugin settings
mcapi.currency.limits.*:
  personal:
    type: boolean
    label: Personal
  skip:
    type: mapping
    label: When to skip balance checks
    mapping:
      auto: 
        type: boolean
        label: Automated transactions
      mass: 
        type: boolean
        label: Mass transactions
      user1: 
        type: boolean
        label: User has permission to 'Configure community accounting'
      owner: 
        type: boolean
        label: User is currency owner
      reservoir: 
        type: boolean
        label: Reservoir account

mcapi.operation.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    subject:
      type: string
      label: Subject
    body:
      type: text
      label: Body
    cc:
      type: string
      label: Copy to

mcapi.state.*:
  type: mapping
  label: Transaction workflow state
  mapping:
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    value:
      type: string
      label: enumerated value

mcapi.type.*:
  type: mapping
  label: Transaction workflow
  mapping:
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    start_state:
      type: string
      label: Initial workflow state

