mcapi.misc:
  type: mapping
  label: 'Other configuration'
  mapping:
    sentence_template:
      type: text
      label: Transaction sentence template
    editable:
      type: boolean
      label: Allow transaction records to be edited
    fields:
      type: mapping
      label: Fields
      mapping:
        participants: 
          type: boolean
          label: Participants
        description: 
          type: boolean
          label: Description
        worth: 
          type: boolean
          label: Worth
        type: 
          type: boolean
          label: Type
        fieldapi: 
          type: boolean
          label: Field API
    exchange_menu:
      type: string
      label: Menu
    ticks_name:
      type: String
      label: Base unit
    worths_delimiter:
      type: string
      label: Delimiter
    zero_snippet:
      type: string
      label: Zero snippet
    counted:
      type: map
      label: Counted transaction states
    child_errors:
      type: mapping
      label: Invalid child transactions
      mapping:
        mail_user1:
          type: string
          label: Send diagnostics to user 1 by mail
        allow:
          type: string
          label: Allow the parent transaction
        log:
          type: string
          label: Log a warning
        show_messages:
          type: string
          label: Show warning messages to user
    indelible:
      type: string
      label: Indelible accounting

mcapi.wallets:
  type: mapping
  label: Wallet settings
  mapping:
    wallet_access:
      type: mapping
      label: Default wallet access setting
      mapping: 
        wallet_default_viewers:
          type: string
          label: 'Visible to'
        wallet_default_payees:
          type: string
          label: 'Default payees'
        wallet_default_payers:
          type: string
          label: 'Default payers'
    display_format:
      type: boolean
      label: 'Display format'
    access_personalised:
      type: boolean
      label: 'Personalised wallet access'
    autoadd:
      type: boolean
      label: 'Auto-create a wallet for every new user'
    add_link_location:
      type: string
      label: 'Location of the link to create new wallets under an entity'

mcapi.currency.*:
  type: mapping
  label: 'Currency configuration'
  mapping:
    id:
      type: string
      label: 'Currency identifier'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Currency Name'
    uid:
      type: integer
      label: Comptroller
    isuance:
      type: string
      label: 'Basis of issuance'
    format:
      type: mapping
      label: Format
      mapping: {}
    zero:
      type: boolean
      label: 'Allow zero transactions'
    color:
      type: string
      label: 'Colour'
    weight:
      type: integer
      label: 'Weight'
    ticks:
      type: float
      label: Ticks

mcapi.state.*:
  type: mapping
  label: Transaction workflow state
  mapping:
    id:
      type: string
      label: State ID
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    counted:
      type: boolean
      label: Counted

mcapi.type.*:
  type: mapping
  label: Transaction workflow
  mapping:
    label:
      type: string
      label: Label
    description:
      type: string
      label: Description
    start_state:
      type: string
      label: Initial workflow state

mcapi.transition.*:
  type: mapping
  label: Transition settings
  mapping: 
    title:
      'type': string
      'label': Title
    tooltip:
      'type': string
      'label': Tooltip
    page_title:
      'type': string
      'label': Page title
    format:
      'type': string
      'label': Transaction display
    twig:
      'type': string
      'label': Template
    button:
      'type': string
      'label': Button text
    cancel_button:
      'type': string
      'label': Cancel button text
    format2:
      'type': string
      'label': Confirm form transaction display
    redirect:
      'type': string
      'label': Redirect path
    twig2:
      'type': string
      'label': Template
    message:
      'type': string
      'label': Success message
#haven't bothered with the notifications because they really belong elsewhere
