<?php

function cc_import_help($path) {
  switch ($path) {
    case 'admin/help#cc_import':
      return t('Provides advice and a simple text box to paste csv style data from your existing spreadsheets. ') .
      t('Assumes user 1 is the balancing account.');
  }
}

/**
 * Implementation of hook_menu)().
 * http://api.drupal.org/api/function/hook_menu/6
 */
function cc_import_menu() {
  $items['admin/marketplace/import'] = array (
    'title' => 'Import Tools',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_balances_form'),
    'access arguments' => array('configure economy'),
    'weight' => 5
  );
  $items['admin/marketplace/import/balances'] = array(
    'title' => 'Import Balances',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );
  $items['admin/marketplace/import/offers'] = array(
    'title' => 'Import Offers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_offers_form'),
    'access arguments' => array('configure economy'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/marketplace/import/wants'] = array(
    'title' => 'Import Wants',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_wants_form'),
    'access arguments' => array('configure economy'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/marketplace/import/launch'] = array(
    'title' => 'LAUNCH MAIL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('launch_form'),
    'access arguments' => array('configure economy'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -50
  );
  return $items;
}


function import_balances_form(&$form_state) {
  //check that no transactions have already taken place
  if (db_result(db_query("SELECT * FROM {cc_transactions}"))) {
    return array('#prefix' => 'You can only import "carried forward" balances before any transactions have been entered on the system.');
  }

  $form['#prefix'] = '<p>' . t("This page allows you to import users' balances and gross incomes for users already on the system. To import users, see the !import_user module.",
    array(
      '!import_user'=>l('import_user', 'http://drupal.org/project/import_user')
    )
  )  . '</p>';
  $form['#prefix'] .= "\n<p>".t("Paste paste 2 or 3 comma separated columns into the field below, the first column should be the uid or username, the second column the current balance, and optionally the third column should be the user's gross income until now (turnover).");
  $form['#prefix'] .= "\n<p>".t("This tools assumes there is only one currency in the system. The second column SHOULD add up to 0 for LETS and other zero balance systems, but this will not be checked." ) . '</p>';
  $form['#prefix'] .= "\n<p>".t("The first line of the field should read (third column is optional): !code", array('!code' => '<blockquote>"UserID","Balance","GrossIncome"</blockquote>"')) . '</p>';
  
  $form['data'] = array (
    '#type' => 'textarea',
    '#title' => 'paste data',
    '#default_value' => $form_state['values']['data'],
    '#required' => TRUE  
  );
  $form['import_balances'] = array (
    '#type' => 'submit',
    '#value' => 'import',
  );
  $form['#redirect'] = 'user/'.variable_get('cc_balancing_account_num', NULL).'/statement';
  return $form;
}

function import_balances_form_validate($form, &$form_state) {
  if (!(variable_get('cc_balancing_account_num', NULL))) {
    form_set_error('data', t('to import balances you need a balancing account. Specify the account number at !admin/marketplace', array('!admin/marketplace'=> l('admin/marketplace','admin/marketplace'))));
  }

  $rows = str_getcsv($form_state['values']['data']);
  check_users($rows);

  foreach ($rows as $rownum => $row) {
    //check integrity of balances, the second field
    if (!intval($row['Balance']) && $row['Balance'] != 0) {
      form_set_error('data', t("balance (second item) on row @num is not an integer", array('@num'=>$key+1)));
    }
  
    //check integrity of gross income, the optional third field
    if (isset($row['GrossIncome'])){
      if (!intval($row['GrossIncome'])) {
        form_set_error('data', t("gross income (third item) on row @rownum must be a positive integer", array('@rownum'=>$rownum+1)));
      } elseif ($row['GrossIncome'] < 0) {
        form_set_error('data', t("gross income (third item) on row @rownum cannot be less than 0", array('@rownum'=>$rownum+1)));
      }
    }
  }
}

function import_balances_form_submit($form, &$form_state) {
  require_once(drupal_get_path('module', 'transactions').'/transactions.inc');
  $rows = str_getcsv($form_state['values']['data']);
  foreach ($rows as $key=>$stats) {
    cc_import_balances_member($stats['UserID'], $stats['Balance'], $stats['GrossIncome']);
  }
}

function import_offers_form(&$form_state) {
  $form['#prefix'] = import_prefix('offers');
  $form['data'] = array (
    '#type' => 'textarea',
    '#title' => 'paste data',
    '#default_value' => $form_state['values']['data'],
    '#required' => TRUE  
  );
  $form['import_balances'] = array (
    '#type' => 'submit',
    '#value' => 'import',
  );
  $form['#redirect'] = 'directory/recent_offers';
  $form['#validate'][] = 'import_offers_wants_form_validate';
  return $form;
}

function import_offers_form_submit ($form, &$form_state) {
  $rows = str_getcsv($form_state['values']['data']);
  foreach ($rows as $row) {
    generate_offer_want_node('offer', $row['UserID'], $row['Description']);
  }
}

function import_wants_form(&$form_state) {
  $form['#prefix'] = import_prefix('wants');
  $form['data'] = array (
    '#type' => 'textarea',
    '#title' => 'paste data',
    '#default_value' => $form_state['values']['data'],
    '#required' => TRUE  
  );
  $form['import_balances'] = array (
    '#type' => 'submit',
    '#value' => 'import',
  );
  $form['#redirect'] = 'directory/recent_wants';
  $form['#validate'][] = 'import_offers_wants_form_validate';
  return $form;
}

function import_wants_form_submit ($form, &$form_state) {
  $rows = str_getcsv($form_state['values']['data']);
  foreach ($rows as $row) {
    generate_offer_want_node('want', $row['UserID'], $row['Description']);
  }
}

function import_offers_wants_form_validate($form, &$form_state) {
  $rows = str_getcsv($form_state['values']['data']);
  check_users($rows);
  foreach ($rows as $rownum => $row) {
    //we've checked the users (field1) already, so now check the description
    if (strlen($row['Description'] > 128)) {
      form_set_error('data', t('The description on row @rownum is more than 128 characters', array('rownum' => $rownum)));
    }
    //now check the taxonomy term exists, and flag an error if it doesn't
    check_terms($row);
  }
  
}

/*
 * Helper Functions
*/

function import_prefix($type) {
  return t("This page allows you to import users' @type for users already on the system.", array('@type' => $type)) . 
  t("There are other ways of doing this, but this is simple and maintained along with the rest of the marketplace module.") . '<br />' .
  //t("If you have 'goods & services' enabled or 'local vs offical' money then it assumes this is a service in local money.") . '<br />' .
  t("Use a spreadsheet tool to prepare a list of user ids, or names, and their @type in one line. ") . 
  t("For aesthetic reasons, there is a 128 character limit on each description. ") . 
  t("Each line should look like this (you must include the header row): !code", array('!code' => '<blockquote><strong>"UserID","Description"</strong></blockquote>')) .
  t("Try importing one or two first.");
}

//check that the user ids or names actually correspond to a user on the system
//coming from the csv all keys and values will be strings, surrounded by quotes
function check_users($rows) {
  foreach ($rows as $rownum => $row){
    $id = $row['UserID'];
    if (is_numeric($id)){
      $member = user_load($id);
    } else {
      $member = user_load($id);
    }
    if (!$member->name) {
      form_set_error('data', t("'UserID' on row @rownum is not a user:@data", array('@rownum'=>$rownum+1, '@data'=>$id)));
    }
  }
}

function check_terms($fields) {
  if ($fields[2]){
    form_set_error("data", "importing categories (third column) hasn't been coded yet", "warning");
  }
  //TODO
  return;
}

if (!function_exists('str_getcsv')) { 
function str_getcsv($input, $delimiter = ",", $enclosure = '"', $escape = "\\") {
  $rows = explode("\n", $input);
  $headers = explode($delimiter, array_shift($rows));
  $all = array();
  while ($row = array_shift($rows)){
    $entry=array();
    $values = explode($delimiter, $row);
    $i=0;
    foreach($values as $v){
      if ($i < count($headers)) $entry[trim($headers[$i], "\"\r")] = trim($v, "\"\r");
      $i++;
    }
    $data[] = $entry;
  }
  return $data;
}}

/*
 * Fields for user_import module NEARLY WORKS!!
*/
function cc_import_user_import_form_field_match() {
  $options = array();
  $options['mutual_credit']['cleared_balance'] = t('Balance');
  $options['mutual_credit']['gross_income'] = t('Gross Income');
  return $options;
}

function cc_import_user_import_data($settings, $update_setting, $column_settings, $type, $field_id, $data, $column_id) {
  $field_match = $type .'-'. $field_id;
  foreach ($settings['field_match'] as $key => $val) {
    if ($val['field_match'] == $field_match) {
      return $data[$key];
    }
  }
}
function cc_import_user_import_after_save($settings, $account, $password, $fields, $updated, $update_setting_per_module) {
  cc_import_balances_member($account->uid, $fields['mutual_credit']['cleared_balance'][0], $fields['mutual_credit']['gross_income'][0]);
}


//generate_transaction_node($title, $payer_uid, $payee_uid, $quantity, $options = array(), $cid=0)
function cc_import_balances_member($uid, $balance, $gross_income=NULL) {
  module_load_include('admin.inc', 'transactions');
  $account = user_load($uid);
  $bal_acc = variable_get('cc_balancing_account_num', 1);
  $options = array(
    'transaction_type' => 'cc_import',
    'starter_uid' => $bal_acc,
  );
  if ($gross_income) {
    generate_transaction_node(t("Gross income"), $bal_acc, $uid, $gross_income, $options, $cid);
    generate_transaction_node(t("Gross expenditure"), $uid, $bal_acc, $gross_income-$balance, $options, $cid);

  } else {//if there is only balance, we do one transaction, which is simply + balance
    if (intval($balance) > 0) {
      drupal_set_message(t("Initial payment to @user of @balance", array('@user' => $account->name, '@balance' => $balance)));
      $transaction = generate_transaction_node(t("Carried Forward"), $bal_acc, $uid, $balance, $options, $cid);
    } elseif (intval($balance) < 0) {
      $balance = abs($balance);
      drupal_set_message(t("Initial payment from @user of @balance", array('@user' => $account->name, '@balance' => $balance)));
      $transaction = generate_transaction_node(t("Carried Forward"), $uid, $bal_acc, $balance, $options, $cid);
    }

  }
}

//provide a checklist and lauch button
function launch_form($form_state) {
  $form['#prefix'] = t('This is where you launch the site by mailing all the members a new password.');
  $form['checklist'] = array(
    '#type' => 'fieldset',
    '#title' => t('Checklist'),
    '#description' => t('All these boxes need to be checked before launching the site')
  );
  $form['checklist']['written'] = array(
    '#title' => t('Launch mail composed'),
    '#type' => 'checkbox',
    '#weight' => 1,
    '#description' => t("Have you composed the 'password_reset' email at !page", array('!page' => l('admin/user/settings', 'admin/user/settings'))),
  );

  $traders = cache_get('cc_trader_list');
  $form['checklist']['membercount'] = array(
    '#title' => t('Trading accounts ready: @num', array('@num' => count($traders->data))),
    '#type' => 'checkbox',
    '#weight' => 2,
    '#description' => t('Are all the members imported and do they have permission to trade?'),
  );
  if (count($traders->data) > 150) {
    $form['checklist']['queue'] = array(
      '#title' => t('Queue module installed'),
      '#type' => 'checkbox',
      '#weight' => 3,
      '#description' => t('If you are mailing many users, you may want to queue them using a module like !module', array('!module', l('Job Queue', 'http://drupal.org/project/job_queue'))),
    );
  }
  $form['checklist']['content'] = array(
    '#title' => t('First content prepared'),
    '#type' => 'checkbox',
    '#weight' => 4,
    '#description' => t('What is the first thing your users will see when they log in for the first time? Is it specially prepared?'),
  );
  $form['checklist']['testmail'] = array(
    '#title' => t('Testmail is sent'),
    '#type' => 'checkbox',
    '#weight' => 6,
    '#description' => t('Have you sent the testmail and imagined yourself a new user who has never seen they system before?'),
  );
  $form['testmail'] = array(
    '#type' => 'fieldset',
    '#title' => t('Test mail'),
    '#description' => t('Send a test mail (not to yourself)'),
  );
  $form['testmail']['uid'] = array(
    '#type' => 'textfield',
    '#title' => 'account to send test to',
    '#description' => t("Enter an account number, but not the one you're using now (@uid)", array('@uid' => $GLOBALS['user']->uid)) .' '.
      t("An email with login instructions will be sent to that account's address"),
    '#submit' => array('cc_import_test_launch'),
    '#element_validate' => array('not_own_account_id')
  );
  $form['testmail']['sendtest'] = array(
    '#type' => 'submit',
    '#weight' => 5,
    '#value' => t('Send test mail'),
    '#submit' => array('cc_import_test_launch')
  );
  $form['launch'] = array(
    '#type' => 'submit',
    '#value' => t('LAUNCH!'),
  );
 return $form;
}
function not_own_account_id(&$element, $form_state) {
  if ($element['#value'] == $GLOBALS['user']->uid) {
    form_error($element, t("You can't send a test mail to the account you are logging in with"));
  }
}

function launch_form_validate($form, $form_state) {
  if ($form_state['values']['op'] != t('LAUNCH!')) return; 
  foreach ($form['checklist'] as $element){
    if (is_array($element) && isset($element['#type']) && $element['#type'] == 'checkbox') {
      if (!$form_state['values'][$element['#name']]) {
        form_set_error($element['#name'], t('All boxes must be ticked to launch'));
      }
    }
  }
}
function cc_import_test_launch($form, $form_state) {
  $account = user_load($form_state['values']['uid']);
  change_and_mail($account);
  drupal_set_message(t('Instructions have been sent to @mail', array('@mail' => $account->mail)));
}

function launch_form_submit($form, $form_state) {
  $traders = cache_get('cc_trader_list');
  foreach(array_keys($traders->data) as $uid){
    change_and_mail(user_load($uid));
  }
  drupal_set_message('Your users have now been notified');
  drupal_uninstall_modules('cc_import');
}

function change_and_mail($account) {
  //$newpass = user_password();
  //user_save($account, array('pass' => $newpass));
  //$account->pass = $newpass;
  _user_mail_notify('password_reset', $account);
}