<?php

/*
 * mcapi_service.module
 *
 * API Wrapper for Xchange Stewards
 * It uses only the mcapi.module for logging transactions and balances.
 * users and currencies are defined outside the system
 * drupal IDs are hidden, using Universal uids ($uuid) and Universal Currency Ids ($ucurrcode)
 * times are converted to ISO 8601
 * This API is for an outside entity,
 *
 * On installation we need to ensure that currency node body is optional!!!
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function mcapi_services_ctools_plugin_api($owner, $api) {
  if ($owner == 'mcapi' && $api == 'services') {
    return array(
      'version' => 3,
      //'file' => 'services.inc', // Optional parameter to indicate the file name to load.
      'path' => drupal_get_path('module', 'mcapi_services'), // If specifying the file key, path is required.
    );
  }
}


/**
 * Implementation of hook_services_resources().
 */
function mcapi_services_services_resources() {
  return array(
    //the mcapi_access function isn't invoked here - access should be decided on the client side
    'transaction' => array(
      'create' => array(
        'help' => t('create a transaction with payer, payee, ucurrcode, quantity and optional properties'),
        'callback' => 'mcapi_service_transaction_create',
        'file' => array('file' => 'inc', 'module' => 'mcapi_services'),
        'access callback' => 'user_access',
        'access arguments' => array('transact'),
        'args' => array(
          0 => array(
            'name' => 'data',
            'optional' => FALSE,
            'source' => 'data',
            'type' => 'struct',
            'description' => t('Universal currency ID'),
          ),
        ),
      ),
      'retrieve' => array(
        'help' => t('Retrieve a transaction using its xid'),
        'callback' => 'mcapi_service_transaction_retrieve',
        'access callback' => 'user_access',
        'file' => array('file' => 'inc', 'module' => 'mcapi_services'),
        'access arguments' => array('transact'),
        'args' => array(
          0 => array(
            'name' => 'xid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => t('Unique transaction ID'),
          )
        ),
      ),
      'update' => array(
        'help' => t('Modify a recorded transaction'),
        'callback' => 'mcapi_service_transaction_update',
        'file' => array('file' => 'inc', 'module' => 'mcapi_services'),
        'access callback' => 'user_access',
        'access arguments' => array('transact'),
        'args' => array(
          0 => array(
            'name' => 'xid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => t('Unique transaction ID'),
          ),
          1 => array(
            'name' => 'data',
            'optional' => FALSE,
            'source' => 'data',
            'type' => 'struct',
            'description' => t('Universal currency ID'),
          ),
        ),
      ),
      'delete' => array(
        'help' => t('Erase a recorded transaction.'),
        'callback' => 'mcapi_service_transaction_delete',
        'access callback' => 'user_access',
        'file' => array('file' => 'inc', 'module' => 'mcapi_services'),
        'access arguments' => array('transact'),
        'args' => array(
          0 => array(
            'name' => 'xid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => t('Unique transaction ID'),
          )
        )
      ),
      //call this with POST services/rest/transactions/get_statement + the three args, ucurrcode=550, ucurrcode=11, rows=4
      'actions' => array(
        'get_statement' => array(
          'help' => t("View a user's recent activity, passing the uuid and the ucurrcode"),
          'callback' => 'mcapi_service_transaction_statement',
          'access callback' => 'user_access',
          'access arguments' => array('transact'),
          'args' => array(
            0 => array(
              'name' => 'uuid',
              'optional' => FALSE,
              'source' => 'data',
              'type' => 'int',
              'description' => t('Universal user ID'),
            ),
            1 => array(
              'name' => 'ucurrcode',
              'optional' => TRUE,
              'source' => 'data',
              'type' => 'varchar',
              'description' => t('Universal currency ID'),
            ),
            2 => array(
              'name' => 'rows',
              'optional' => TRUE,
              'source' => 'data',
              'type' => 'int',
              'description' => t('Number of results'),
            )
          ),
          'file' => array('file' => 'inc', 'module' => 'mcapi_services')
        )
      )
    ),
    'balances' => array(
      'retrieve' => array(
        'help' => t("Get a user's balances, in a given currency"),
        'callback' => 'mcapi_service_user_balances',
        'access callback' => 'user_access',
        'access arguments' => array('transact'),
        'args' => array(
          0 => array(
            'name' => 'uuid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => t('Universal user ID'),
          ),
          1 => array(
            'name' => 'ucurrcode',
            'optional' => TRUE,
            'source' => 'data',
            'type' => 'varchar',
            'description' => t('Universal currency ID'),
          ),
        ),
        'file' => array('file' => 'inc', 'module' => 'mcapi_services')
      )
    )
  );
}

function mcapi_services_form_currency_form_alter(&$form, $form_state, $currency) {
  $form['ucurrcode'] = array(
    '#title' => t('Universal currency ID'),
    '#description' => t('What is the unique code of this currency when referenced from outside?'),
    '#type' => 'textfield',
    '#default_value' => isset($currency->ucurrcode) ? $currency->ucurrcode : '',
    '#weight' => -3
  );
}


/*
 * helper functions
 * get the currency object from the universal currency ID
 */
function mcapi_service_currency_lookup($ucurrcode){
  $currencies = currencies_load();
  foreach ($currencies as $currency) {
    if ($currency->ucurrcode == $ucurrcode) return $curr;
  }
}


/*
 * implements hook_form_FORM_ID_alter
 * adds a field to the user form so that each user has a unique ID
 */
function mcapi_services_form_user_profile_form_alter(&$form, $form_state) {
  $form['uuid'] = array(
    '#title' => t('Name in external schema'),
    '#description' => t('What is the unique code for this user when referenced from outside?'),
    '#type' => 'textfield',
    '#default_value' => isset($account->uuid) ? $account->uuid : '',
    '#weight' => 3
  );
}
function mcapi_services_user_insert(&$edit, $account, $category) {//and update
  db_query("REPLACE INTO {mcapi_universal_ids} (did, universal_id, type) VALUES (:did, :u_id, 'user')",
    array(
      ':did' => $account->uid,
      ':u_id' => $account->uuid ? $account->uuid : $account->uid
    )
  );
}
function mcapi_services_user_delete(&$edit, $account, $category) {
  db_query("DELETE FROM {mcapi_universal_ids} WHERE did = %d AND type = 'user'",
     array(':utid' => $account->uid)
  );
}
function mcapi_services_user_view($account, $view_mode, $langcode) {
  $account->content['uuid'] = array(
    '#title' => t('Universal user ID'),
    '#type' => 'user_profile_item',
    '#value' => $account->uuid
  );
}


//returns the drupal user object. used to return currency nodes from $ucid
function mcapi_service_universal_lookup($universal_id, $type){
  $did = db_query(
    "SELECT did FROM {mcapi_universal_ids} WHERE universal_id = :u_id AND type = :type",
    array(':u_id' => $universal_id, ':type' => $type)
  )->fetchField();
}



/*
 * implements hook_entity_insert
 */
function mcapi_services_currency_insert($currency, $type) {
  mcapi_services_currency_update($currency, $type);
}

/*
 * implements hook_entity_update
 */
function mcapi_services_currency_update($currency, $type) {
  if ($type == 'currency') {
    $unid = isset($currency->ucurrcode) ? $currency->ucurrcode : $currency->currcode;
    db_query("REPLACE INTO {mcapi_universal_ids} (did, universal_id, type) VALUES (:did, :u_id, 'currency')",
      array(
        ':did' => $currency->currcode,
        ':u_id' => $currency->ucurrcode
      )
    );
  }
}
/*
 * implements hook_entity_delete
 */
function mcapi_services_entity_delete($currency, $type) {
  if ($type == 'currency') {
    db_query("DELETE FROM {mcapi_universal_ids} WHERE did = :did AND type = 'currency'",
      array(':did' => $currency->currcode)
    );
  }
}
