<?php // ;id:

/*
 * Permitted users can design their own transaction forms, hopefully all valid!
 */

/*
 * implements hook_menu
 */
function mcapi_forms_menu() {
  module_load_include('inc', 'mcapi_forms');
  //all the admin menu items are generated via the ctools export-ui plugin
  $items = array();
  $mcapi_forms = mcapi_forms_load(NULL, TRUE);
  //one menu callback for each form.
  foreach($mcapi_forms as $form) {
    if (!empty($form->disabled)) continue;
    $settings = &$form->data;
    $menu_link = &$settings['architecture']['menu_link'];
    $items[$settings['architecture']['path']] = array(
      'title' => empty($settings['experience']['title']) ? $settings['experience']['sure_title'] : $settings['experience']['title'],
      'page callback' => 'drupal_get_form',
      'page arguments' => array(//2nd and subsequent are are the $form_state['build_info']
        'mcapi_forms_form',
        //in case the form needs to load a transaction, extract it from the path
        array_search('%transaction', explode('/', $settings['architecture']['path'])),//may return NULL
        $form//we put the whole settings array in the menu item because ctools performance is very poor
      ),
      'access callback' => strtok($settings['architecture']['access'], ':'),
      'access arguments' => array(strtok(':')),
      'menu_name' => is_numeric($menu_link) ? 'navigation' :$menu_link,
      'type' =>is_numeric($menu_link) ? $menu_link : MENU_NORMAL_ITEM,
      'file' => 'mcapi_forms.inc',
    );
  }

  $default_tabs_supplied = 0;
  //make one of these the default tab on transact
  foreach ($items as $key => $item) {
    if (substr($key, 0 , 9) == 'transact/') {
      $default_tab_needed = TRUE;
      if ($item['type'] == MENU_DEFAULT_LOCAL_TASK) {
        $items[$key]['weight'] = -1;
        $default_tabs_supplied++;
      }
    }
  }
  if (isset($default_tab_needed)) {
    if (empty($default_tabs_supplied)) drupal_set_message(t("There is no default tab under path 'transact/'"));
    elseif ($default_tabs_supplied > 1) drupal_set_message(t("There is more than one default tab under path 'transact/'"));
  }
  return $items;
}

/*
 * implements hook_menu_alter
 * alters the menu item provided by ctools so it can be used for context
 */
function mcapi_forms_menu_alter(&$items) {
  foreach (mcapi_forms_load(NULL, TRUE) as $form) {
    //remove the default tab under 'transact/'
    if (substr($form->data['architecture']['path'], 0 , 9) == 'transact/') {
      unset($items['transact/default']);
      //replace the 'transact' item form with whichever of the forms has default tab
      if ($form->data['architecture']['menu_link'] == MENU_DEFAULT_LOCAL_TASK) {
        $items['transact'] = $items[$form->data['architecture']['path']];
        $items['transact']['type'] = MENU_NORMAL_ITEM;
      }
    }
    break;
  }
  $items['admin/accounting/forms']['weight'] = -1;
  $items['admin/accounting/forms/list/%ctools_export_ui/edit']['_tab'] = TRUE;
  $items['admin/accounting/forms/list/%ctools_export_ui/edit']['tab_parent'] = 'admin/accounting/forms/list/%';
  $items['admin/accounting/forms/list/%ctools_export_ui/edit']['context'] = MENU_CONTEXT_INLINE;
  unset($items['admin/accounting/display']);
  unset($items['admin/accounting/display/default']);
}

/*
 * implements hook_forms
 * $args is an mcapi_form and an optional transaction
 */
function mcapi_forms_forms($form_id, $args) {
  $forms['mcapi_forms_form'] = array(
    'callback' => 'transaction_form',
    'callback arguments' => $args
  );
  return $forms;
  
}


/*
 * implements hook_form_FORMID_alter
 * Alter the mcapi form editing form
 */
function mcapi_forms_form_ctools_export_ui_edit_item_form_alter(&$form, &$form_state) {
  if ($form_state['plugin']['schema'] != 'mcapi_forms') return;
  $form['#validate'][] = 'mcapi_forms_template_validate';
  $form_state['redirect'] = 'admin/accounting/forms';

  $form['advice'] = array(
    '#type' => 'markup',
    '#markup' => t('Test your form before enabling for users!'),
    '#weight' => 25
  );
  $form['buttons']['#prefix'] = '<div>';
  $form['buttons']['#suffix'] = '</div>';
}


/*
 * implements hook_form_FORMID_alter
 * The building of the transaction form is done in the alter phase of building the basic form.
 * This means that any alter hooks for the basic form are also run.
 */
function mcapi_forms_form_mcapi_forms_form_alter(&$form, &$form_state, $form_id) {
  form_load_include($form_state, 'inc', 'mcapi_forms');
  $mcapiform = &$form_state['build_info']['args'][MCAPIFORM_BUILD_INFO_ARG];
  //set the page title if this form is not being displayed in a block
  //ascertains whether the active path corresponds to this mcapi_form
  $parts = explode('/', current_path());
  //reverse calculate the path
  $map = explode('/', $mcapiform->data['architecture']['path']);
  foreach($map as $key => $part) {
    if (strpos($part, '%') === 0) $parts[$key] = $part;
  }
  $titles = &$mcapiform->data['experience'];
  if ($parts == $map) {
    drupal_set_title(
      empty($titles['title']) ?
        mcapi_locale($titles['sure_title'], 'sure_title') :
        mcapi_locale($titles['title'], 'title')
    );
  }
  if (!empty($form_state['storage']) && $form_state['step'] == 1) {
    $form_state['values'] = $form_state['storage'];
  }
  _mcapi_forms_form_mcapi_forms_form_alter($form, $form_state, $form_id);
}

/*
 * Implements hook_block_info
 */
function mcapi_forms_block_info() {
  $mcapi_forms = mcapi_forms_load();
  $blocks = array();
  foreach ($mcapi_forms as $mcapi_form) {
    if ($mcapi_form->data['architecture']['use_block'] && empty($mcapi_form->disabled)) {
      $blocks[$mcapi_form->name] = array(
        'info' => t('Transaction form:') . ' ' .$mcapi_form->name,
        'cache' => DRUPAL_CACHE_PER_USER
      );
    }
  }
  return $blocks;
}

/*
 * Implements hook_block_view
 */
function mcapi_forms_block_view($delta) {
  //load the form and check access first
  $mcapi_form = mcapi_forms_load($delta);
  //it's generally a bad idea to show the form in block on its own page
  if (current_path() == $mcapi_form->data['architecture']['path']) return;
  if (!user_access('transact')) return;
  return array(//if these seem inverted its because drupal_get_form loads the inc file
    'subject' => $mcapi_form->data['experience']['title'],
    'content' => drupal_get_form('mcapi_forms_form', new_transaction(), $mcapi_form),
  );
}

/*
 * Implements hook_mcapi_info_types
 *
 */
function mcapi_forms_mcapi_info_types() {
  $mcapi_forms = mcapi_forms_load();
  foreach($mcapi_forms as $mcapi_form) {
    if ($mcapi_form->data['experience']['title']) {
      $types[] = $mcapi_form->name;
    }
  }
  return $types;
}

/*
 * Implements hook_mcapi_info_drupal_permissions
 */
function mcapi_forms_mcapi_info_drupal_permissions() {
  return array(
    'design transaction forms' => array(
      'title' => t('Design transaction forms'),
      'description' => t('Create and edit the forms used to record and edit transactions'),
    )
  );
}

/*
 * Implements hook_theme
 */
function mcapi_forms_theme($existing, $type, $theme, $path) {
  return array(
    'mcapi_form' => array(
      'render element' => 'form',
    ),
  );
}

/*
 * callback specified in the export_ui plugin
 * the formID is actually ctools_export_ui_edit_item_form
 */
function mcapi_edit_mcapi_form(&$form, &$form_state) {
  cache_clear_all('mcapi_forms', 'cache');
  form_load_include($form_state, 'admin.inc', 'mcapi_forms');
  form_load_include($form_state, 'inc', 'mcapi');//contains the validation functions for the default form elements
  $form_state['build_info']['files']['menu'] = drupal_get_path('module', 'mcapi_forms') .'/mcapi_forms.admin.inc';
  $form_state['build_info']['files']['ctools'] = drupal_get_path('module', 'ctools') .'/includes/export.inc';
  $form['#tree'] = TRUE;
  return _edit_mcapi_form($form, $form_state);
}

/*
 * load an mcapi_form by name, using ctools
 * it seems that ctools isn't doing any caching
 */
function mcapi_forms_load($name = NULL) {
  //$items = cache_get('mcapi_forms');
  static $items;
  if (empty($items)) {
    ctools_include('export');
    $items = ctools_export_crud_load_all('mcapi_forms');
    drupal_alter('mcapi_forms', $items);
    //cache_set('mcapi_forms', $items);
  }
  if ($name && isset($items[$name])) {
    return $items[$name];
  }
  return $items;
}

/*
 * Implements ctools hook_ctools_plugin_directory
 */
function mcapi_forms_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/export_ui';//directory
  }
}
/*
 * Implements ctools hook_ctools_plugin_api
 */
function mcapi_forms_ctools_plugin_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'mcapi_forms'),
  );
}

/**
 * Find out whether the logged in user has one of the given roles
 */
function mcapi_access_check_roles($rid) {
  global $user;
  $roles = array_keys($user->roles);
  $roles[] = DRUPAL_AUTHENTICATED_RID;
  return in_array($rid, $roles);
}


/*
 * implements hook_form_FORMID_alter
 */
function mcapi_forms_form_system_theme_settings_alter(&$form, $form_state) {
  $form['tab_element'] = array(
    '#title' => t('Css menu tab identifier'),
    '#description' => t("The second stage of the the transaction form works best when the menu tabs are hidden.") .' '. 
      t("Write the css identifier for the div on this page containing the menu items which 'List', 'Update' & 'Settings'.") .' '.
      t("Don't forget the leading . or #"),
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('tab_element')
  );
}

/*
 * The second stage of the transaction should NOT show the tabs such as view, edit etc
 */
function mcapi_hide_tabs() {
  $data = array(
    '#tag' => 'style',
    '#value' => theme_get_setting('tab_element') .'{display:none;}'
  );
  drupal_add_html_head($data, 'hide_tabs');
}

/*
 * this needs a bit of thought...
 */
function mcapi_path_validate(&$element, &$form_state) {}

function mcapi_forms_form_field_ui_field_edit_form_alter(&$form, $form_state) {
  //because default values are best set in the forms
  unset($form['instance']['default_value_widget']);
  //because this module removes the #theme_wrapper from form elements, so the title is invisible anyway
  unset($form['instance']['label']);
  //ditto
  unset($form['instance']['description']);
}

