<?php 
/* themes the balances for a given user.
 * Available variables
 * $balances is an array of the form:
 * Array (
    [$cid] => Array (
      [cleared_balance] => themed quantity
      [pending_dif] => themed quantity
      [gross_in] => themed quantity
      [gross_out] => themed quantity
      [max_in] => themed quantity
      [max_out] => themed quantity
      [rating] => themed quantity
      [max] => themed quantity
      [min] => themed quantity
    )
  )
 * also $currencies = array() //generated by preprocess
 * plus the usual
 */
if (!count($balances)) {
  print t("Yet to trade.");
  return;
}

$rows = array(
  0 => array(0 => t('Cleared balance')),
  1 => array(0 => t('Total income')),
  2 => array(0 => t('Spending limit'))
);
foreach ($balances as $cid => $data) {
  if (isset($currencies[$cid]->data['ratings'])) {
    $rows[3] = array(0 => t('Ratings'));
  }
}

$headings = array(0 => '');
foreach ($balances as $cid => $set) {
  $headings[] = $currencies[$cid]->title;
  foreach($set as $value) {
    $rows[0][$cid] = $set['cleared_balance'];
    $rows[1][$cid] = $set['gross_in'];
    $rows[2][$cid] = $set['max_out'];
    if (isset($currencies[$cid]->data['ratings'])) {
      $rows[3][$cid] = $set['rating'];
    }
  }
}

print theme('table', $headings, $rows);
?>