id: user.field_exchanges
uuid: a02e4720-f5d8-44b3-8f00-d2d6151518d6
status: true
langcode: en
name: field_exchanges
entity_type: user
type: entity_reference
settings:
  target_type: mcapi_exchange
module: entity_reference
locked: true
cardinality: '-1'
translatable: false
indexes: {  }
