op_title: Undo
page_title: 'Are you sure?'
format: certificate
twig: ''
button: 'Yes I''m sure'
cancel_button: Cancel
feedback:
format2: certificate
twig2: ''
redirect: ''
message: The transaction has been deleted
send: 0
subject: 'A transaction was deleted'
body: 'no tokens were a available to write this mail'
cc: carboncopy@drupal.org
