id: escro
uuid: 1b93baa9-95b9-4f05-8900-b13ccc9657cc
name: Euro
issuance: exchange
uid: '1'
reservoir: '1'
display:
  type: decimal
  granularity: 2
  widget: CURRENCY_WIDGET_SINGLEFIELD
  select:
  delimiter:
  prefix: €
  suffix:
  zero:
access:
  membership: 'user_chooser_segment_perms:transact'
  trader_data: 'user_chooser_segment_perms:transact'
  system_data: 'user_chooser_segment_perms:transact'
view_transaction_states:
  1:
    transaction_access_callback_perm_transact: transaction_access_callback_perm_transact
    transaction_access_callback_perm_manage_all: transaction_access_callback_perm_manage_all
  0:
    transaction_access_callback_perm_manage_all: transaction_access_callback_perm_manage_all
access_operations:
  view: {  }
  undo:
    transaction_access_callback_perm_manage_all: transaction_access_callback_perm_manage_all
weight: '-9'
status: true
langcode: en
