sentence_template: '[mcapi:payer] paid [mcapi:payee] [mcapi:worth] for [mcapi:description]. [transaction:links]'
mix_mode: true
worths_delimiter: '|'
child_errors:
  mail_user1: mail_user1
  allow: 0
  watchdog: watchdog
  show_messages: show_messages
wallet_access:
  wallet_default_viewers: role:authenticated
  wallet_default_payees: role:authenticated
  wallet_default_payers: role:authenticated
wallet_short_names: true
wallet_access_personalised: true
