entity_types:
  'user:user': 1
  'mcapi_exchange:mcapi_exchange': 10
viewers: role:authenticated
payees: role:authenticated
payers: role:authenticated
unique_names: 0
display_format: '!o: !w'
access_personalised: 0
autoadd_name: My wallet
