entity_types:
  'user:user': 1
  'mcapi_exchange:mcapi_exchange': 10
viewers: role:authenticated
payees: role:authenticated
payers: role:authenticated
unique_names: false
access_personalised: true
autoadd_name: My wallet
