sentence_template: '[mcapi:payer] paid [mcapi:payee] [mcapi:worth] for [mcapi:description]. [transaction:links]'
mix_mode: true
worths_delimiter: '|'
child_errors:
  mail_user1: mail_user1
  allow: 0
  watchdog: watchdog
  show_messages: show_messages
wallet_access:
  wallet_default_viewers: {  }
  wallet_default_payees: {  }
  wallet_default_payers: {  }
wallet_unique_names: 1
wallet_access_personalised: 0
wallet_autoadd: 0
wallet_one: 1
type: null
types:
  mcapi_exchange: mcapi_exchange
  node: node
  user: user
