base_field: xid
base_table: mcapi_transactions_index
core: 8.x
description: ''
status: true
display:
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: 1
    display_options:
      path: wallet/%
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 1
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          slave: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: 0
          id: 0
          total_pages: ''
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: 9
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: 1
          row_class_special: 1
          override: 1
          sticky: 0
          caption: ''
          summary: ''
          description: ''
          columns:
            xid: xid
            created: created
            partner_id: partner_id
            balance: balance
            operations: operations
            outgoing: outgoing
            incoming: incoming
          info:
            xid:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            created:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            partner_id:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            balance:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            operations:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            outgoing:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
            incoming:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
          default: '-1'
          empty_table: 0
      row:
        type: fields
      fields:
        xid:
          id: xid
          table: mcapi_transactions_index
          field: xid
          relationship: none
          group_type: group
          admin_label: ''
          label: Serial
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          set_precision: false
          precision: 0
          decimal: .
          separator: ','
          format_plural: 0
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          plugin_id: numeric
          provider: views
        created:
          id: created
          table: mcapi_transactions_index
          field: created
          plugin_id: date
          provider: views
        partner_id:
          id: partner_id
          table: mcapi_transactions_index
          field: partner_id
          plugin_id: standard
          provider: views
        incoming:
          id: incoming
          table: mcapi_transactions_index
          field: incoming
          relationship: none
          group_type: group
          admin_label: ''
          label: Credit
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 0
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: worth
          provider: mcapi
        outgoing:
          id: outgoing
          table: mcapi_transactions_index
          field: outgoing
          relationship: none
          group_type: group
          admin_label: ''
          label: Debit
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 0
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          machine_name: 0
          plugin_id: worth
          provider: mcapi
        balance:
          id: balance
          table: mcapi_transactions_index
          field: balance
          plugin_id: balance
          provider: mcapi
        operations:
          id: operations
          table: mcapi_transactions_index
          field: operations
          relationship: none
          group_type: group
          admin_label: ''
          label: Operations
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          mode: ajax
          plugin_id: transaction_operations
          provider: mcapi
      filters: {  }
      sorts:
        created:
          id: created
          table: mcapi_transactions_index
          field: created
          order: DESC
          relationship: none
          group_type: group
          admin_label: ''
          exposed: false
          expose:
            label: ''
          granularity: second
      title: 'Statement'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments:
        wallet_id:
          id: wallet_id
          table: mcapi_transactions_index
          field: wallet_id
          relationship: none
          group_type: group
          admin_label: ''
          default_action: 'not found'
          exception:
            value: all
            title_enable: 0
            title: All
          title_enable: 0
          title: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: 0
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: 0
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: 0
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: 0
          not: 0
          plugin_id: user_uid
          provider: user
label: 'wallet history'
module: views
id: wallet_history
tag: ''
uuid: 3ffde51e-024a-4781-9500-d0c8cf484f1e
langcode: en
