base_field: xid
base_table: mcapi_transactions
core: 8.x
description: 'A starter view for Community Accounting'
status: true
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 1
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          slave: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: 10
          offset: 0
          id: 0
          total_pages: ''
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: 9
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: 1
          row_class_special: 1
          override: 1
          sticky: 0
          caption: ''
          summary: ''
          description: ''
          columns:
            xid: xid
          info:
            xid:
              sortable: 0
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: 0
              responsive: ''
          default: '-1'
          empty_table: 0
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        serial:
          id: serial
          table: mcapi_transactions
          field: serial
          relationship: none
          group_type: group
          admin_label: ''
          label: Serial
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: standard
          provider: views
        created:
          id: created
          table: mcapi_transactions
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          label: Created
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          date_format: html_date
          custom_date_format: ''
          timezone: ''
          plugin_id: date
          provider: views
        name_1:
          id: name_1
          table: users
          field: name
          relationship: payer
          group_type: group
          admin_label: ''
          label: Payer
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: 1
          overwrite_anonymous: 1
          anonymous_text: ''
          format_username: 1
          plugin_id: user_name
          provider: user
        name:
          id: name
          table: users
          field: name
          relationship: payee
          group_type: group
          admin_label: ''
          label: Payee
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          link_to_user: 1
          overwrite_anonymous: 1
          anonymous_text: ''
          format_username: 1
          plugin_id: user_name
          provider: user
        worths:
          id: worths
          table: mcapi_transactions
          field: worths
          relationship: none
          group_type: group
          admin_label: ''
          label: Amounts
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          separator: ''
          plugin_id: worths
          provider: mcapi
        state:
          id: state
          table: mcapi_transactions
          field: state
          relationship: none
          group_type: group
          admin_label: ''
          label: State
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: mcapi_state
          provider: mcapi
        type:
          id: type
          table: mcapi_transactions
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          label: Type
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          plugin_id: standard
          provider: views
        operations:
          id: operations
          table: mcapi_transactions
          field: operations
          relationship: none
          group_type: group
          admin_label: ''
          label: Operations
          exclude: 0
          alter:
            alter_text: 0
            text: ''
            make_link: 0
            path: ''
            absolute: 0
            external: 0
            replace_spaces: 0
            path_case: none
            trim_whitespace: 0
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: 0
            max_length: ''
            word_boundary: 1
            ellipsis: 1
            more_link: 0
            more_link_text: ''
            more_link_path: ''
            strip_tags: 0
            trim: 0
            preserve_tags: ''
            html: 0
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: 1
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: 1
          empty: ''
          hide_empty: 0
          empty_zero: 0
          hide_alter_empty: 1
          mode: ajax
          plugin_id: transaction_operations
          provider: mcapi
      filters:
        parent:
          id: parent
          table: mcapi_transactions
          field: parent
          relationship: none
          group_type: group
          admin_label: ''
          operator: '='
          value: '0'
          group: '1'
          exposed: false
          expose:
            operator_id: false
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: 0
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: boolean
          provider: views
      sorts:
        serial:
          id: serial
          table: mcapi_transactions
          field: serial
          relationship: none
          group_type: group
          admin_label: ''
          order: DESC
          exposed: false
          expose:
            label: ''
          plugin_id: standard
          provider: views
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        payee:
          id: payee
          table: mcapi_transactions
          field: payee
          relationship: none
          group_type: group
          admin_label: Payee
          required: 1
          plugin_id: standard
          provider: views
        payer:
          id: payer
          table: mcapi_transactions
          field: payer
          relationship: none
          group_type: group
          admin_label: Payer
          required: 1
          plugin_id: standard
          provider: views
      arguments:
        currcode:
          id: currcode
          table: mcapi_transactions_worths
          field: currcode
          relationship: none
          group_type: group
          admin_label: ''
          default_action: ignore
          exception:
            value: all
            title_enable: 0
            title: All
          title_enable: 0
          title: ''
          breadcrumb_enable: 0
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: 0
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: 0
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: 0
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          glossary: 0
          limit: '0'
          case: none
          path_case: none
          transform_dash: 0
          break_phrase: 0
          plugin_id: string
          provider: views
      filter_groups:
        operator: AND
        groups: {  }
      title: 'Finished transactions'
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: 1
    display_options:
      path: transactions
label: 'Member transactions'
module: views
id: mcapi_transactions
tag: 'Community Accounting'
uuid: 7ba3bb18-3608-44e3-a418-240b11424ab6
langcode: en
