command_strings: "pay [transaction:quantity] to [transaction:payee] for [transaction:description]\r\nrequest [transaction:quantity] from [transaction:payer] for [transaction:description]"
response_success: 'Success. Your balance is @balance'
syntax_error: 'Syntax error'
twitter_response: 'Success. Your balance is @balance'
