<?php
//$Id: balances.tpl.php,v 1.3 2010/12/08 11:43:18 matslats Exp $

/* themes the balances for a given user.
 * Available variables
 * $balances is an array of the form:
 * Array (
    [$cid] => Array (
      [cleared_balance] => themed quantity
      [pending_dif] => themed quantity
      [gross_in] => themed quantity
      [gross_out] => themed quantity
      [max_in] => themed quantity
      [max_out] => themed quantity
    )
  )
 * also $currencies = array() //generated by preprocess
 * plus the usual
 */
if (!count($balances)) {
  print t("Yet to trade.");
  return;
}

$rows = array(
  0 => array(0 => t('Cleared balance')),
  1 => array(0 => t('Pending difference')),
  2 => array(0 => t('Total income')),
  3 => array(0 => t('Transactions')),
);

$header = array(0 => '');
foreach ($balances as $cid => $set) {
  $header[] = $currencies[$cid]->name;
  foreach($set as $value) {
    $rows[0][$cid] = $set['cleared_balance'];
    $rows[1][$cid] = $set['pending_dif'];
    $rows[2][$cid] = $set['gross_in'];
    $rows[3][$cid] = $set['count'];
  }
}

print theme('table', compact('header', 'rows'));
?>