mcapi.1stparty.*:
  type: mapping
  label: 'Mcapi form configuration'
  mapping:
    id:
      type: string
      label: 'Mcapiform identifier'
    exchange:
      type: string
      label: 'Exchange'
    title:
      type: label
      label: 'Form title'
    status:
      type: boolean
      label: Enabled
    type:
      type: string
      label: 'Transaction type'
    mywallet:
      type: mapping
      label: 'My Wallet'
      mapping:
        widget:
          type: string
          label: 'Widget'
        unused:
          type: string
          label: 'Unused behaviour'
    partner:
      type: mapping
      label: 'Settings for partner field'
      mapping:
        selection:
          type: string
          label: 'Users to choose from'
        preset:
          type: integer
          label: 'Preset trading partner'
    direction:
      type: mapping
      label: 'Direction of payment'
      mapping:
        preset:
          type: string
          label: 'Preset direction'
    description:
      type: mapping
      label: 'Reason for payment'
      mapping:
        preset:
          type: string
          label: 'Preset description'
        placeholder:
          type: string
          label: 'Placeholder'
    fieldapi_presets:
      type: mapping
      label: 'Other presets'
    experience:
      type: mapping
      label: 'Experience'
      mapping:
        twig:
          type: text
          label: Main form
        button:
          type: text
          label: Button label
        preview:
          type: text
          label: Preview mode
