<?php
//replaces the variable 'default_currency' with an array of ctools exportable objects

/*
 * Implements ctools hook_ctools_plugin_directory
 */
function mcapi_currencies_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/export_ui';//directory
  }
}
/*
 * Implements ctools hook_ctools_plugin_api
 */
function mcapi_currencies_ctools_plugin_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'mcapi_currencies'),
  );
}

function mcapi_currencies_menu() {
  $items['currency/add'] = array(
    'title' => 'Declare currency',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('currency_form'),
    'access arguments' => array('declare currency'),
    'type' => MENU_CALLBACK,
    'file' => 'mcapi.inc',
  );
  $items['currency/%currency/edit'] = array(
    'title' => 'Modify currency',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('currency_form', 1),
    'access callback' => array('currency_access'),
    'access arguments' => array('edit', 1),
    'type' => MENU_CALLBACK,
    'file' => 'mcapi.inc',
  );
  return $items;
}

/*
 * Implements hook_menu_alter
 * Gets rid of the menu item for editing the default currency variable
 * which has been replaced by the ctools item
 */
function mcapi_currencies_menu_alter(&$items) {
  unset($items['admin/accounting/currency']);
}


/*
 * Implements ctools export_ui callback
 */
function mcapi_currencies_form(&$form, &$form_state) {
  ctools_include('export'); //this is needed to load up the existing currency, at least on an ajax reload
  form_load_include($form_state, 'admin.inc', 'mcapi', 'currencies');
  $currency = &$form['#currency'];
  $currency = isset($form_state['values']) ? (object)$form_state['values'] : $form_state['item']->data;
  if (empty($currency->name)) {
    $currency = currency_default();
    $currency->uid = $GLOBALS['user']->uid;
    $currency->name = '';
    $currency->format = '';
    $currency->currcode = user_password();
  }
  else {
    drupal_set_title( !empty($currency->name) ? $title = t("Edit currency '@name'", array('@name' => $currency->name)) : t('Declare currency') );
  }

  _mcapi_currency_form($form, $form_state);

  $form['name']['#element_validate'] = array('mcapi_currency_validate_name');
  $passed = empty($form_state['values']['uid']) ? $currency->uid : $form_state['values']['uid'];
  $owner = empty($passed) ? $GLOBALS['user']->uid : $passed;
  $owner = user_load($owner);
  $form['uid'] = array(
    '#type' => 'textfield',
    '#title' => t('Declared by'),
    '#maxlength' => 60,
    '#autocomplete_path' => 'user/autocomplete',
    '#default_value' => $owner->name,
    '#element_validate' => array('mcapi_validate_username'),
    '#required' => TRUE,
    '#weight' => 4
  );

  //nasty design flaw around radio buttons which means ajax rebuilds them wrong
  if (arg(0) == 'system') {
    unset($form['accounting']['update_mode']['#title']);
  }

  if (isset($currency->currcode)) {
    $form['buttons']['submit']['#value'] = t('Update');
  }
}

/*
 * implements hook_form_FORMID_alter
 * because if you add #submit handlers before this then it doesn't do so automatically
 */
function mcapi_form_mcapi_currencies_form_alter() {
  $form['#submit'][] = 'currencies_recache';
}



/*
 * Implements hook_mcapi_info_drupal_permissions
 */
function mcapi_currencies_mcapi_info_drupal_permissions() {
  return array(
    'configure all currencies' => array(
      'title' => t('Configure all currencies'),
      'description' => t('Edit the properties of any currency')
    ),
    'declare currency' => array(
      'title' => t('Declare currency'),
      'description' => t('Create a new currency'),
    )
  );
}



function transaction_validate_currency_access($form, $form_state) {
  $transaction = &$form_state['transaction'];
  $currency = currency_load($transaction->currcode);
  $participants = array('payer', 'payer');
  foreach ($participants as $participant) {
    if (!currency_access('use', $currency, $transaction->$participant)) {
      form_set_error($participant, t("!name is not permitted to use @currency", array(
        '!name' => format_username(user_load($transaction->$participant)),
        '@currency' => $currency->name
      )));
    }
  }
}


function currencies_load_all() {
  ctools_include('export');
  $all = ctools_export_crud_load_all('mcapi_currencies');
  //unpack them
  foreach($all as $name => $currency) {
    if (empty($currency->disabled)) {
      _currency_divisions_array($currency->data);
      $currencies[$name] = $currency->data;
    }
  }
  return $currencies;
}


/*
 * forces a reload of currencies into the cache and static variable
 * not for use by script. Instead use currencies_recache in currencies.admin.inc
 */
function clear_currency_cache(){
  cache_clear_all('currencies', 'cache');
  drupal_static_reset('currencies');
}

/*
 * callback declared in mcapi_currencies_ui.class.php
 */
function mcapi_currencies_form_validate() {
  //debug('mcapi_currencies_form_validate function is empty');
}

/*
 * callback from ctools export_ui plugin
 */
function mcapi_currencies_form_submit($form, &$form_state) {
  form_state_values_clean($form_state);
  //I would have thought this database key would have been provided automacically
  //since the field was created automatically
  $form_state['item']->currcode = $form_state['values']['info']['currcode'];
  $form_state['item']->data = (object)$form_state['values'];
  register_shutdown_function('currencies_recache');
}

/*
 * returns a form element for picking a currency
 */
function currency_picker_element($default_value, $multiple = FALSE, $currencies = array()) {
  return array(
    '#title' => t('Currency'),
    '#type' => 'select',
    '#options' => currency_picker_element_options($currencies),
    '#default_value' => $default_value,
    '#multiple' => $multiple,
  );
}

function currency_picker_element_options($currencies = array()) {
  if (empty($currencies)) {
    $currencies = currencies_load();
  }
  foreach ($currencies as $currency) {
    $options[$currency->info['currcode']] =
      $currency->name;
  }
  return $options;
}