#this won't install because the transactions plugin isn't found
uuid: f9cdce69-ed7c-47cc-8309-153e0d577f38
langcode: en
status: true
dependencies:
  config:
    - group.type.exchange
  module:
    - mcapi_exchanges
id: exchange-transactions
label: 'Group transactions'
description: 'Adds transactions to exchanges'
group_type: exchange
content_plugin: transactions


