#this doesn't include per-plugin settings
#TODO this isn't used, since it is all just thirdpary settings in the currency.
#hopefully it can be used here for translating...
mcapi.fees:
  type: mapping
  label: 'Fees'
  mapping:
    curr_id:
      type: string
      label: Currency
    rate:
      type: integer
      label: Per Cent
    types:
      type: sequence
      label: Transaction Types
      sequence: { }
    round_up:
      type: boolean
      label: Round up
    payer:
      type: boolean
      label: Charge payer
    payee:
      type: boolean
      label: Charge Payee
    target:
      type: integer
      label: Target wallet
    description:
      type: text
      label: Transaction description 

