id: d7_transaction_settings
label: Accounting settings
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - mcapi_sentence
process:
  sentence_template:
    plugin: mcapi_sentence
    source: mcapi_sentence
destination:
  plugin: config
  config_name: mcapi.settings
