id: d7_transaction_settings
label: Accounting settings
migration_tags:
  - Drupal 7
provider: migrate_drupal
source:
  plugin: d7_mcapi_settings
process:
  xid: xid
  serial: serial
  type: type
  description: description
  uid: uid
  state: state
  created: created
  changed: changed
destination:
  plugin: entity:mcapi_transaction
migration_dependencies:
  required:
    - d7_user
  optional:
    - d7_field_instance
