#this doesn't include per-plugin settings
mcapi_currency.*.third_party.mcapi_limits:
  type: mapping
  label: 'Limits settings'
  mapping:
    plugin:
      type: string
      label: ID of the limits plugin
    plugin_settings:
      type: sequence
      label: Settings for the plugin
    personal:
      type: boolean
      label: Personal
    skip:
      type: mapping
      label: When to skip balance checks
      mapping:
        auto:
          type: boolean
          label: Automated transactions
        mass:
          type: boolean
          label: Mass transactions
        user1:
          type: boolean
          label: User has permission to 'Configure community accounting'
        owner:
          type: boolean
          label: User is currency owner
    prevent:
      type: boolean
      label: Prevent transactions which transgress limits.
    #these are temp until rules is implemented
    warning_mail:
      type: mail
      label: Mail notification
    prevented_mail:
      type: mail
      label: Mail notification
