#this doesn't include per-plugin settings
#TODO this isn't used, since it is all just thirdpary settings in the currency.
#hopefully it can be used here for translating...
mcapi.limits.*:
  type: mapping
  label: 'Limits settings'
  mapping:
    personal:
      type: boolean
      label: Personal
    skip:
      type: mapping
      label: When to skip balance checks
      mapping:
        auto:
          type: boolean
          label: Automated transactions
        mass:
          type: boolean
          label: Mass transactions
        user1:
          type: boolean
          label: User has permission to 'Configure community accounting'
        owner:
          type: boolean
          label: User is currency owner
    display_relative:
      type: boolean
      label: Display perspective
    prevent:
      type: boolean
      label: Prevent transaction
    warning_mail:
      type: mail
      label: Mail notification
    prevented_mail:
      type: mail
      label: Mail notification