
mcapi.signatures.*:
  type: mapping
  label: Signature settings
  mapping: 
    both:
      'type': boolean
      'label': Payer & payee (The current user signs automatically)
    exman:
      'type': boolean
      'label': The exchange manager
