id: pay
title: 'Pay someone'
status: 1
type: default
partner:
  #@todo user chooser is deprecated
  selection: 'user_chooser_segment_perms:transact'
  preset: ''
direction:
  preset: outgoing
  widget: radios
  incoming: 'Incoming'
  outgoing: 'Outgoing'
worths:
  preset:
    credunit:
      currcode: credunit
      value: 0
description:
  preset: ''
  placeholder: ''
experience:
  twig: "Pay: {{ partner }}\n{{ worths }}\nfor {{ description }}"
  button: Preview
  preview: page
