id: pay
title: 'Pay someone'
status: 1
type: default
partner:
  user_chooser_config: 'user_chooser_segment_perms:transact'
  preset: ''
direction:
  preset: outgoing
  widget: radios
  incoming: 'Incoming'
  outgoing: 'Outgoing'
worths:
  preset:
    credunit:
      currcode: credunit
      value: 0
description:
  preset: ''
  placeholder: ''
step1:
  twig1: "Pay: {{ partner }}\n{{ worths }}\nfor {{ description }}"
  button1: Preview
  next1: page
step2:
  format2: '0'
  twig2: ''
  button2: Confirm
  next2: page
  redirect: ''
redirect: null
langcode: en
direction:
  preset: outgoing
  widget: radios
  incoming: ''
  outgoing: ''
message: 'The transaction has been logged'
