<?php

/**
 * implements hook_transaction_alter
 * add a 2% charge to both payer and payee
 *
 * @todo this should be done with rules or completed here
 */
function mcapi_rules_mcapi_transaction_assemble_alter($transaction) {
  $fees = \Drupal::config('mcapi.fees');
  if (!$fees->get('rate')) {
    return;
  }
  if ($fees->get('payer')) {
    $payers[] = $transaction->payer->target_id;
  }
  if ($fees->get('payee')) {
    $payers[] = $transaction->payee->target_id;
  }
  foreach ($payers as $payer) {
  dsm(1);
    $value = $transaction->worth->{$fees->get('curr_id')} * $fees->get('rate');
    $props = [
      'creator' => 1,//user id
      'type' => 'auto',//references \Drupal\mcapi\Entity\Type
      'worth' => [
        0 => [
          'curr_id' => $fees->get('curr_id'),
          'value' => $fees->get('round_up') ? ceil($value/100) : floor($value/100)
        ]
      ],
      'payer' => $payer,
      'payee' => $fees->get('target'),
      'description' => 'TEMP',//$fees->get('reason')
    ];
    $transaction->children[] = \Drupal\mcapi\Entity\Transaction::create($props + ['payer' => $transaction->payer->target_id]);
  }
}